### PR TITLE
task(monorepo): move deps to correct sub-packages

### PR DESCRIPTION
**Pull request by meandavejustice**
## Because

- fixing a goof from 05a00a0aeee1e3bf2441b7f279a1c9fa5e089ed0

## Issue that this pull request solves

Closes: #6433

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).

### CODE REVIEW

**Comment by dannycoates** [comment]
also https://github.com/mozilla/fxa/commit/047c96ea58895de2d2d0517acb9844bd27e6f6f6

**Comment by meandavejustice** [comment]
@dannycoates just pushed the fixes for 047c96e

**Review by dannycoates — APPROVED** [review]

**Comment by dannycoates** [comment]
@meandavejustice also the `@types` from https://github.com/mozilla/fxa/commit/b7d726cbfa67302b017bdee2dcf726e38c62e428 if you get a chance

**Comment by meandavejustice** [comment]
@dannycoates Just pushed the fix for the `@types`

**Pull request merged**
