### PR TITLE
Release 1.182.0

### PR DESCRIPTION
**Pull request by 6a68**
Opening a PR to merge the train back into the main branch, per our [release process docs](https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/release-process) :+1:

### CODE REVIEW

**Comment by jodyheavener** [comment]
Huh, looks like the additional [CHANGELOG files](https://github.com/mozilla/fxa/pull/6071) didn't make it in? (not import for the release, just an observation)

**Comment by jodyheavener** [comment]
Huh, looks like the additional [CHANGELOG files](https://github.com/mozilla/fxa/pull/6071) didn't make it in? (not import for the release, just an observation)

**Comment by 6a68** [comment]
Hmm, that's weird @jodyheavener. I followed the instructions in the release doc:

1. `git clone git@github.com:mozilla/fxa fxa.tagging`
2. `./release.sh`

Not sure why the new files weren't included 🤷

**Comment by jodyheavener** [comment]
Oh well. If it's still not working when I release next week I'll poke at it. It's not hurting anything in the meantime.

**Pull request merged**
