### PR TITLE
fix(support): don't exit the form when you hit enter

### LINKED ISSUE #5377: Hitting "enter" in the support form exits
Noticed that if you're in a text field or dropdown on the `/support` form it will exit the form. If anything it should submit the form, or at least confirm that you want to exit.

I believe it's because the Cancel button in that form needs a `type="button"` on it.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1925)
┆Issue Number: FXA-1925

### PR DESCRIPTION
**Pull request by jodyheavener**
Closes #5377

### CODE REVIEW

**Comment by jodyheavener** [comment]
I'd like to test this with a native Enter key press, but I'm having trouble setting that up with our current test setup. Something like...

```
const typeNative = thenify(function(selector, key) {
  return this.parent
    .findByCssSelector(selector)
    .sendKeys(Key[key])
    .end();
});

// usage
.then(typeNative('#topic_chosen a.chosen-single', 'ENTER'))
```

But not sure where to look up Selenium keys.

**Comment by jackiemunroe** [comment]
@jodyheavener could you rebase this onto master so that it using `yarn` instead of `npm` for package management?

**Comment by jackiemunroe** [comment]
> I'd like to test this with a native Enter key press, but I'm having trouble setting that up with our current test setup. Something like...
> 
> ```
> const typeNative = thenify(function(selector, key) {
>   return this.parent
>     .findByCssSelector(selector)
>     .sendKeys(Key[key])
>     .end();
> });
> 
> // usage
> .then(typeNative('#topic_chosen a.chosen-single', 'ENTER'))
> ```
> 
> But not sure where to look up Selenium keys.
https://www.selenium.dev/documentation/en/webdriver/keyboard/

**Comment by jodyheavener** [comment]
Hmm, yeah, I got it working by installing the `selenium-webdriver` package but I thought I'd be able to import something from one of our existing testing deps. Just not sure how it's all set up with Intern 🤔

**Comment by 6a68** [comment]
> Hmm, yeah, I got it working by installing the `selenium-webdriver` package but I thought I'd be able to import something from one of our existing testing deps. Just not sure how it's all set up with Intern 🤔

@jodyheavener Intern uses a browser driver called leadfoot, which has a `pressKeys` method you can use: https://theintern.io/leadfoot/module-leadfoot_Session.html#pressKeys

There's a ton of reusable code in fxa-content-server/tests/functional/lib/helpers.js, you can skim the list of helpers at the bottom of the file. Surprisingly, though, I don't see one that handles non-printable characters.

**Comment by jodyheavener** [comment]
awesome thanks @6a68!

**Pull request merged**
