### PR TITLE
feat(metrics): add a flow.doNotSync flow event when users decline to sync

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes https://github.com/mozilla/application-services/issues/2088
Fixes https://github.com/mozilla/fxa/issues/3344

@shane-tomlinson @vbudhram r?

cc @davismtl 

Logs: 

```
11|content-server PORT 3030  | {"event":"flow.doNotSync","flow_id":"b7a7f3572c1cdf951a0465c37ad8c926127e04fec0c6a1fe9fd5ffff0e8b9812","flow_time":7964,"hostname":"Vlads-MacBook-Pro.local","locale":"en","op":"flowEvent","pid":20622,"time":"2019-11-18T16:20:35.667Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0","v":1,"context":"fx_desktop_v3","entrypoint":"fxa_discoverability_native"}
 ```

### CODE REVIEW

**Comment by davismtl** [comment]
Will this event find its way to Amplitude?

**Comment by shane-tomlinson** [comment]
> Will this event find its way to Amplitude?

Good point, it's not on the [list of events that is sent to Amplitude](https://github.com/mozilla/fxa/blob/28b3857f5e66732e02c883e13398c1f53972a332/packages/fxa-content-server/server/lib/amplitude.js#L120), @vladikoff, changing to r- to fix that.

**Comment by vladikoff** [comment]
Possible values: 

```
flow.choose-what-to-sync.doNotSync
flow.would-you-like-to-sync.doNotSync
```

@irrationalagent which amplitude group should we use?

**Comment by irrationalagent** [comment]
So today we have these events where cwts = "choose what to sync"
image

If this new option is going to be included as part of the choose what to sync view (or whatever we are going to call it in the future) then we should probably follow this convention, like `fxa_reg - cwts_do_not_sync`. If it will be both in the reg view AND login view, the we would also need `fxa_login - cwts_do_not_sync`. We don't have any cwts metrics for login yet, so this would be the first.

**Comment by davismtl** [comment]
> If it will be both in the reg view AND login view, the we would also need fxa_login - cwts_do_not_sync. We don't have any cwts metrics for login yet, so this would be the first.

Should we be also including mirror `cwts` events from registration for login flows?

**Comment by vladikoff** [comment]
@irrationalagent new events are as follows: 

for login:

> {"op":"amplitudeEvent","event_type":"fxa_login - cwts_do_not_sync","time":1574102710315,"user_id":"8d8391675897439da64ca47d159f23e2","device_id":"4084547173854162bbbc4a8fd8faab3e","session_id":1574102705811,"app_version":"150.2","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"10fe3bc2f1418c67a0193f2bf6f7b5f1640a7d23fff6ede95a223742edea2dfc","ua_browser":"Firefox","ua_version":"72.0","$append":{"experiments":["email_first_treatment"]}}}

for registration:

>  fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - cwts_do_not_sync","time":1574103066560,"device_id":"0f2bb775a6d3419db2e677d80d256fbe","session_id":1574103053404,"app_version":"150.2","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"53b38584b4d25cad0e791c85c81a15d30964ae11f33d7d7efa2a66c2e848cfc1","ua_browser":"Firefox","ua_version":"72.0","$append":{"experiments":["email_first_treatment","signup_code_treatment"]}}}

**Comment by irrationalagent** [comment]
> Should we be also including mirror `cwts` events from registration for login flows?

yes we should make sure that those are covered in the login flow now. that seems like broader scope than this PR, so ill open a separate issue.

**Pull request merged**
