### PR TITLE
commit to add connected devices

### PR DESCRIPTION
**Pull request by farhan787**
@vbudhram connected devices table...

### CODE REVIEW

**Comment by farhan787** [comment]
@vbudhram your review please.

**Comment by shane-tomlinson** [comment]
@vbudhram and @farhan787 - what more needs to happen with this PR to get it merged?

**Comment by vbudhram** [comment]
@farhan787 Please take a look at https://github.com/mozilla/fxa/commit/7555ba929fb1f56a65d4468c4c9a8159da659429, this the logic need to correctly unit test security events. You can pull the commit into this PR or as needed.

The main issue I found was that you needed to call the `beforeRender` function in the beforeEach. I also added some logic to correctly setup the mocks needed to load attached clients. Let me know if that works.

**Comment by farhan787** [comment]
> The main issue I found was that you needed to call the `beforeRender` function in the beforeEach. 

@vbudhram is it compulsory to call the `beforeRender` in beforeEach for every unit test file ?

**Comment by vbudhram** [comment]
> call the beforeRender in beforeEach for every unit test file?

Yea should be fine since in this case you are explicitly testing logic in the `beforeRender`.

**Comment by farhan787** [comment]
@vbudhram could you review it please ?

**Comment by shane-tomlinson** [comment]
Hey @vbudram - mind reviewing these?

**Comment by farhan787** [comment]
@vladikoff isn't this supposed to merge ?

**Comment by farhan787** [comment]
@vbudhram could you please look into this, if I should make a new PR for this ? Is there something wrong with this work ?

**Comment by vbudhram** [comment]
Hey @farhan787 Unfortunately, this feature got pushed to beginning next year. I don't think there is anything else for you to do. Once this year bugs get completed, I will circle back to it.

Thanks again for helping with this!

**Comment by farhan787** [comment]
@vbudhram I'd like to continue working on this, I can ping you in January 2020 and complete this one if that's ok ?

**Pull request closed without merging**
