### PR TITLE
Import fxa-amplitude-send into monorepo

### PR DESCRIPTION
**Pull request by dannycoates**
This PR doesn't actually change any dependencies or integration into CI, etc. It's just the commits from the OG repo. Done with [lerna import --preserve-commit](https://github.com/lerna/lerna/tree/master/commands/import#readme)

### CODE REVIEW

**Comment by dannycoates** [comment]
needs `cmake` :/

**Comment by dannycoates** [comment]
dang, there's more https://github.com/mozilla/fxa-amplitude-send/blob/master/Dockerfile-node#L3

**Comment by dannycoates** [comment]
ok, deps taken care of in #3219

**Comment by dannycoates** [comment]
Someone with more powers is going to have to merge this since there's no way these commits will get signed.

**Comment by 6a68** [comment]
I'll do it

**Comment by 6a68-mozilla-owner** [comment]
/me ducks into a phone booth, emerges in glitchy super suit

**Pull request merged**
