### PR TITLE
feat(payments): Payments server shell.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
This is a standalone payments server with some code copied over
from the content-server. Ideally we'd be able to share some of the
code directly, perhaps via fxa-shared, though this was a quick way
of getting started.

@ianb, @lmorchard - What do you think about this approach instead of #919, I think it could provide a lot more flexibility.

I'd like to remove the copied code, and the shared dependencies does bring up the questions @philbooth raised in #941, I didn't want to tackle either of those right now.

### CODE REVIEW

**Comment by lmorchard** [comment]
Grabbed the branch, got it running. I'm tempted to say we might be better off rolling our own webpack & babel config, rather than use create-react-app.

On the bright side, they made it easier to use Sass for stylesheets than the last time I checked. And it would be nice to let someone else manage most of the React build stack.

But, they make some (IMO) weird decisions in `react-scripts` like [insisting on clearing the terminal output on every change with no config or switch to disable](https://github.com/facebook/create-react-app/issues/2495) while running the dev server. That'll probably make it an awkward roommate while running `./pm2 logs` assuming we run the dev server alongside everything else.

If it's helpful, I can make a PR against this PR or something with a small webpack config & dependencies

**Comment by lmorchard** [comment]
> But, they make some (IMO) weird decisions in react-scripts like insisting on clearing the terminal output on every change with no config or switch to disable while running the dev server. That'll probably make it an awkward roommate while running ./pm2 logs assuming we run the dev server alongside everything else.

Huh, actually... I tried switching to the react-scripts dev server in `servers.json` and `mysql_servers.json`:

https://github.com/lmorchard/fxa/commit/0e953c7a331f42432801e3d23677783389265cfd

It's not too bad. I had to toss in another env var to stop it from opening a browser tab on startup. But, it only tries to clear the terminal if there's a real TTY, which `./pm2 logs` doesn't supply. Maybe we can roll with create-react-app for awhile? IIRC, it's easy enough to "eject" and customize from there.

**Comment by shane-tomlinson** [comment]
@lmorchard - mind an r? and we can iterate to get this production ready?

**Comment by shane-tomlinson** [comment]
> Grabbed the branch, got it running. I'm tempted to say we might be better off rolling our own webpack & babel config, rather than use create-react-app.
> 
> That said, it would be nice to let someone else manage most of the React build stack. On the bright side, they made it easier to use Sass for stylesheets than the last time I checked. Used to be, you had to run Sass in a separate process to build CSS.

TBH, I don't know what I'm doing with React, I used create-react-app because I knew it existed and it made it easy for me to set up the app. I'd be happy to see something more minimal, or at least a dev server that makes use of the express app so that things are kind-of-sort-of-at-least-somewhat-related to how they'd be run in prod.

**Comment by lmorchard** [comment]
> I'd be happy to see something more minimal, or at least a dev server that makes use of the express app so that things are kind-of-sort-of-at-least-somewhat-related to how they'd be run in prod.

We can iterate on this - nice thing about create-react-app is it offers an `npm run eject` command that copies all their scripts and dependencies into our project so we can go off in our own direction and customize things to taste

**Pull request merged**
