### PR TITLE
chore(mysql): Upgrade to MySQL 8.0.31

### PR DESCRIPTION
**Pull request by jbuck**
## Because

-

## This pull request

-

## Issue that this pull request solves

Closes: # (issue number)

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

### CODE REVIEW

**Comment by clouserw** [comment]
Looks like all the tests are failing with:

> Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
>  image cache not found on this host, downloading cimg/mysql:8.0.31
>
> Error response from daemon: manifest for cimg/mysql:8.0.31 not found: manifest unknown: manifest unknown

I restarted them in case this was transient.

**Comment by jbuck** [comment]
Hm, I should just switch to the 8.0 alias: https://circleci.com/developer/images/image/cimg/mysql

**Comment by clouserw** [comment]
Failing on https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/test/oauth/db/index.js#L86 now.  Maybe we should revisit what our actual tables have too since these defaults change

**Comment by jbuck** [comment]
utf8 == utf8mb3 so I updated the test to match MySQL 8.0 defaults

**Review by chenba — APPROVED** [review]

**Pull request merged**
