### PR TITLE
chore(tests): enable subscribe test on dev

### PR DESCRIPTION
**Pull request by dannycoates**
Thanks @chenba for fixing the stripe metadata!

### CODE REVIEW

**Review by vbudhram — APPROVED** [review]

**Comment by dannycoates** [comment]
I think we're hitting some kind of a race on the stripe customer here. From the auth-server logs:

```
{
  "status": 404,
  "errno": 176,
  "path": "/v1/oauth/mozilla-subscriptions/customer/billing-and-subscriptions",
  "lang": "en-US,en;q=0.5",
  "agent": "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0",
  "remoteAddressChain": ["127.0.0.1"],
  "t": 8,
  "uid": "b77f544c87b547c384c4f0717577e555",
  "keys": false,
  "method": "get"
}
```

where 176 is `UNKNOWN_SUBSCRIPTION_CUSTOMER`

according to the logs it looks like this is happening in prod too

**Comment by chenba** [comment]
> I think we're hitting some kind of a race on the stripe customer here. From the auth-server logs:
> 
> ```
> ...
> ```
> 
> where 176 is `UNKNOWN_SUBSCRIPTION_CUSTOMER`
> 
> according to the logs it looks like this is happening in prod too

That's an expected error.  The payments frontend uses that error to determine whether a FxA user is a subscriber.

**Comment by chenba** [comment]
When the test intermittently fails for me locally it's not the same failure as CI.  😩 

```
    Error: expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      15 |     await relier.clickEmailFirst();
      16 |     await login.submit();
    > 17 |     expect(await relier.isPro()).toBe(true);
         |                                  ^
      18 |   });
      19 |
      20 |   test('content-server mocha tests', async ({ target, page }, { project }) => {
```

**Comment by dannycoates** [comment]
> When the test intermittently fails for me locally

I needed to restart my services to pick up the stripe capabilities change

**Comment by chenba** [comment]
> > When the test intermittently fails for me locally
> 
> I needed to restart my services to pick up the stripe capabilities change

Yeah, they've been restarted.  And the test more often than not does pass.

**Comment by biancadanforth** [comment]
FWIW I ran the test on this branch too, and while I did get a timeout error, it was on an earlier line, and I had to run the test 80 times to get one failure. Could be a difference in hardware as I am on an M1 Max MBP.

```
  1) [local] › misc.spec.ts:4:3 › severity-1 › subscribe and login to product ======================

    Timeout of 90000ms exceeded.

    Pending operations:
      - page.fill at pages/products/index.ts:5:22

    page.fill: Target closed
    =========================== logs ===========================
    waiting for selector "[data-testid="name"]"
    ============================================================

       9 |     await relier.goto();
      10 |     await relier.clickSubscribe();
    > 11 |     await subscribe.setFullName();
         |                     ^
      12 |     await subscribe.setCreditCardInfo();
      13 |     await subscribe.submit();
      14 |     await relier.goto();

        at SubscribePage.setFullName (/Users/bdanforth/Projects/fxa/packages/functional-tests/pages/products/index.ts:5:22)
        at /Users/bdanforth/Projects/fxa/packages/functional-tests/tests/misc.spec.ts:11:21

```

**Comment by biancadanforth** [comment]
I found this [GitHub discussion](https://github.com/microsoft/playwright/issues/10832) where a user was having a similar issue in Firefox only, which ultimately [converged on the solution of not waiting for navigation explicitly](https://github.com/microsoft/playwright/issues/11167#issuecomment-1005848094) as that is handled automatically with page.click navigations.

I noticed there's a similar pattern of `Promise.all(..., waitForNavigation)` for all 3 failures, so I removed that call and reran the tests 240 times and it has passed each time. Worth a shot @dannycoates ?

**Comment by biancadanforth** [comment]
Also @chenba had an interesting thought that this could perhaps be related to #11269 , which @bbangert plans to investigate during this sprint.

**Comment by dannycoates** [comment]
sorry for the red herring, y'all. it was failing because there was no firestore emulator running. 🤦‍♂️

**Comment by biancadanforth** [comment]
> sorry for the red herring, y'all. it was failing because there was no firestore emulator running. 🤦‍♂️

Thanks for the update -- though the firestore emulator runs by default in local dev, so it was running when I ran the test locally. I guess it wasn't running in your CI environment? I also don't understand how that would cause an intermittent failure rather than a permafail. 🤔

**Comment by dannycoates** [comment]
it failed locally occasionally because stripe was rate limiting me

**Pull request merged**
