### PR TITLE
fix(totp): fixes bug where totp form is enabled with no input

### PR DESCRIPTION
**Pull request by samaksh02**
## Because

-Continue"/ "Finish" button becomes enabled when user clicks outside the code field at the first attempt

## This pull request

-solves the above issue. 

## Issue that this pull request solves

Closes: #7738

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

### CODE REVIEW

**Review by vbudhram — CHANGES_REQUESTED** [review]
@samaksh02 Thanks for your PR, it works for me locally.

Before merging could you update the commit message to follow pattern in contributing [doc](https://github.com/mozilla/fxa/blob/main/CONTRIBUTING.md#git-commit-guidelines). Something along the lines of `fix(totp): fixes bug where totp form is enabled with no input` etc.

**Comment by samaksh02** [comment]
hi @vbudhram . i have updated the message.

**Comment by samaksh02** [comment]
hey. i have made some mistakes here while commiting into main branch. closing this pull request. will open a new pull request.

**Comment by samaksh02** [comment]
here is the link for the new pull request. 
https://github.com/mozilla/fxa/pull/8803

**Pull request closed without merging**
