### PR TITLE
Remove chilts

### PR DESCRIPTION
**Pull request by chilts**

### CODE REVIEW

**Comment by chilts** [comment]
Thanks again to everyone for all the support you guys and Mozilla have shown me along the way. Means a huge amount to me now and I'm sure it will in the future too. It's been a blast.

dave-null

**Comment by pdehaan** [comment]
This makes me sad.

**Comment by chilts** [comment]
@pdehaan I thought the 'Dave Null' joke would be a healthy distraction. :)

**Comment by rfk** [comment]
:-(

**Pull request merged**
