### PR TITLE
FxA-33 - Choose What to Sync

### PR DESCRIPTION
**Pull request by vladikoff**
@ryanfeeley updated design based on feedback from https://github.com/mozilla/fxa-content-server/issues/3183

Needs a review, I'm not sure I'm sold on the compact view. see attached

TODO:
- [x] Fix the shadow in the Device image on sides
- [x] Finalize the checkbox view
- [x] @ryanfeeley r?
- [x] @billmaggs r?

### CODE REVIEW

**Comment by vladikoff** [comment]
WIP on extra fields: 
image

**Comment by vladikoff** [comment]
@ryanfeeley please review: 

image

image

image

**Comment by ryanfeeley** [comment]
#### Questions:
* Is label clickable too? (wrap in label tag)
* Please add 40px space above devices images

##### For sync datatypes could we do (two column still):
* [ ] Bookmarks
* [ ] History
* [ ] Tabs
* [ ] Passwords
* [ ] Add-ons
* [ ] Preferences

Add-ons and Preferences sync only across desktop versions of Firefox

**Comment by vladikoff** [comment]
> Is label clickable too? (wrap in label tag) 

Yeah

> Please add 40px space above devices images

image

20px on mobile, otherwise not enough space for iOS:

image

**Comment by ryanfeeley** [comment]
@vladikoff Something like this but with bigger font like you already have for checkboxes?
choose-what-to-sync

**Comment by ryanfeeley** [comment]
@vladikoff Is email in mobile view bolder?

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1218497

**Comment by vladikoff** [comment]
> @vladikoff Is email in mobile view bolder?

Yes, it is consistent with the mini view on OAuth login: (try logging in on https://getpocket.com/login?ep=3)
image

Do you want that changed? Everywhere or just here?

**Comment by ryanfeeley** [comment]
@vladikoff Hmm… the responsive subhead is actually a different font altogether (Clear Sans). @johngruen intentional?

**Pull request merged**
