### PR TITLE
task(fxa-content-server): account for legal-docs new format

### PR DESCRIPTION
**Pull request by meandavejustice**
## This pull request

- update scripts to account for legal-docs repo changes coming in https://github.com/mozilla/legal-docs/pull/1502

## Issue that this pull request solves

Closes: #6902 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

## Other information (Optional)

For testing you'll need to update the `legal-docs` dependency to point to the restructured commit, linked above.

### CODE REVIEW

**Comment by clouserw** [comment]
Please ping me after this is approved but before this lands.  It will require some coordination with the L10n team

**Review by vbudhram — COMMENTED** [review]
@meandavejustice I was to generate the updated legal pdfs with the script, however I had to modify [fullpath](https://github.com/mozilla/fxa/blob/f760d7231a401ad8b29e46a5bf25ff850e5eb659/_scripts/legal-md-to-pdf.sh#L57) to `fullpath="${path}/../../assets/legal"` in order to get it created.

I have never really used this script before but I ran it from fxa-content-server. Is this correct?

**Comment by meandavejustice** [comment]
@vbudhram I didn't have to modify that myself when I was running it, but I'm happy to update it if it makes it easier to run

**Review by vbudhram — APPROVED** [review]
> I didn't have to modify that myself when I was running it, but I'm happy to update it if it makes it easier to run

Hm not really sure who/when this gets run, but maybe it doesn't need to be updated. Once the linked legal doc PR lands, the tests here should pass?

**Comment by meandavejustice** [comment]
The upstream work is to be resumed in January https://github.com/mozilla/legal-docs/pull/1502#issuecomment-748365051

**Pull request merged**
