### PR TITLE
chore(deps): enable renovate for all monorepo packages

### PR DESCRIPTION
**Pull request by 6a68**
Let's just see how this goes

### CODE REVIEW

**Comment by bbangert** [comment]
Looks fine so far! What's next?

**Comment by 6a68** [comment]
> Looks fine so far! What's next?

Good question. I'm going to try simplifying the config a little bit, and try to figure out how to run _all_ the tests without merging to master.

**Comment by 6a68** [comment]
I'm going to try to land this, and we can revert if it breaks stuff.

**Comment by 6a68** [comment]
> I'm going to try to land this, and we can revert if it breaks stuff.

Going to wait until after the work week to potentially break stuff ;-)

**Pull request merged**
