### PR TITLE
chore(l10n): adjust locales for completeness

### PR DESCRIPTION
**Pull request by clouserw**
## Because

- We should make sure the locales we offer are somewhat complete

## This pull request

- Enables/disables locales based on agreed upon thresholds

## Issue that this pull request solves

Closes: # FXA-7305

### CODE REVIEW

**Comment by clouserw** [comment]
Would like someone from @mozilla/subplat-devs to review too

**Review by bcolsson — APPROVED** [review]
Noting here I may send a request for Tatar to be reactivated in the near future. Translations are waiting approval but currently bottlenecked. (ETA sometime May)

**Review by LZoog — APPROVED** [review]
100% coverage in Serbian now?! Nice.

**Review by sardesam — APPROVED** [review]
LGTM! 👍

**Pull request merged**
