### PR TITLE
Eye Password Experiment

### PR DESCRIPTION
**Pull request by ryanfeeley**
We would like to learn if users who show the password field are
struggling less, and also learn if a new toggle style is more
successful. We may use results to inform a choice about show password
in platform.

### CODE REVIEW

**Comment by vladikoff** [comment]
Is it not already proven that "text" (especially localized) works better than "icons"?

**Comment by shane-tomlinson** [comment]
> Is it not already proven that "text" (especially localized) works better than "icons"?

Seems like a good thing to AB test, we could put the localized text into an `alt` attribute for the curious.

**Comment by ryanfeeley** [comment]
It's not proven but a (likely) theory proposed by Luke W. I have two more
treatments in mind. Will add today!

**Comment by rfk** [comment]
I'm marking this ready for review, if we're confident that the feature and plan is sufficiently well-specified then we may as well merge this and we can figure out how and when to prioritize the implementation work.

**Comment by ryanfeeley** [comment]
@rfk Would this bug be a better first step? https://github.com/mozilla/fxa-content-server/issues/3524

**Comment by rfk** [comment]
I'm going to close this in favour of https://github.com/mozilla/fxa/pull/134, please re-open if they're in fact slightly different things.

**Comment by ryanfeeley** [comment]
@rfk Safe assumption.

**Pull request closed without merging**
