### PR TITLE
fix(css): fixes #2130 - Account flow sync checkbox style tweak

### LINKED ISSUE #2130: [Train 143]The 'Logins and Passwords' from new account flow synchronization is not splitted correctly
Environment:
Builds: Stage [Train 143];
Devices: Android, iOS;

## Steps to reproduce:

1. Start an account creation flow using valid credentials;
2. Tap on 'Create account' button;
3. Observ the 'Choose what to synchronize' list;

## Expected results:
The list doesn't have any visual defect;

## Actual results:
The 'Logins and Password' option is not splitted correctly.

## Notes:
- Not reproducible on Windows;
- Not reproducible on production;
- photo: 
Screenshot_20190809-102510

### PR DESCRIPTION
**Pull request by LZoog**
fix for #2130

image

image

### CODE REVIEW

**Comment by vladikoff** [comment]
@LZoog is it possible to check this in Firefox for iOS?

**Comment by LZoog** [comment]
I had some issues setting up `firefox-ios`, Carthage was skipping a particular framework build (SwiftyJSON) that I had to manually build.

@vladikoff, I'm having a hard time reproducing the CWTS screen in mobile sign up even when copying the parameters used to see this in desktop, every time I've tried I hit the e-mail confirmation screen instead. Do we have docs somewhere of various flows and how to see them?

I replicated the HTML/CSS/copy from this screen into another view and checked in iOS, and it looks good to me / like the screenshot above. I had to do a similar CSS fix for the delete account checkboxes and those also look good.

**Comment by vladikoff** [comment]
@LZoog if you do a "sign up" on Firefox iOS does that give you CWTS?

**Comment by LZoog** [comment]
Woo, I'm able to see this now in XCode to confirm it's good to go.

image

**Pull request merged**
