### PR TITLE
feat(fxa-auth-server): move time to a new line

### PR DESCRIPTION
**Pull request by flozender**
## Because

- #8013 wanted the time to have its own line below the date.

## This pull request

- Accomplishes the goal

## Issue that this pull request solves

Closes: #8013 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

image

### CODE REVIEW

**Comment by flozender** [comment]
I'm trying to run `yarn test` to check if any tests need to be modified but it just says `keys file already exists` and the process exits. Would appreciate any pointers here.

**Comment by jodyheavener** [comment]
Hey @flozender that's odd that it's exiting for you. I also get that same message, but the tests proceed. Can you make sure that when running auth-server tests you have the process stopped in PM2? (refer to [these docs](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/README.md#testing)). Also just to clarify, you're running `yarn test` in the `fxa-auth-server` package, correct?

**Review by vbudhram — CHANGES_REQUESTED** [review]
@flozender Thanks for PR! I think this looks good but just needs our tests updated. I guess we never checked for a timestamp so it would be good to add this.

In [test/local/senders/email.js](https://github.com/mozilla/fxa/blob/e497d1f12c017296e6b1c3fcdac2d4a7f2fc8993/packages/fxa-auth-server/test/local/senders/email.js#L95), you can add a mock value for `time` and `date` and then update the corresponding template tests to verify that they render correctly.

You should be able to follow this pattern https://github.com/mozilla/fxa/blob/e497d1f12c017296e6b1c3fcdac2d4a7f2fc8993/packages/fxa-auth-server/test/local/senders/email.js#L1110.

**Comment by flozender** [comment]
Thanks, @jodyheavener, I wasn't stopping the `fxa-auth-server` so the tests weren't working. @vbudhram, I was able to add tests to make sure the date and time were getting rendered properly.

**Review by vbudhram — APPROVED** [review]
@flozender Thank you! This LGTM 👍🏽

@jodyheavener I'll defer merging when you are ready.

**Review by jodyheavener — APPROVED** [review]
This is awesome. Way to go!

**Pull request merged**
