### PR TITLE
fix(metrics): DENG-4405 Convert event extras to string

### PR DESCRIPTION
**Pull request by akkomar**
## Because

- We want to log backend events in the right format. [Glean schema expects event extras to be strings](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/main/schemas/glean/glean/glean.1.schema.json#L109-L118). We are currently logging some of them as booleans, which causes these pings to fail validation.

## This pull request

- Fixes backend event logging code to convert extras to strings. To do this, we need to regenerate Glean telemetry code with the latest glean_parser. This PR bumps minimum Glean.js version to `5.0.3` that includes parser version that correctly handles event extras.
- I regenerated all Glean files to keep them in sync. To make this easier to read, changes are split into two commits:
  - First one addresses the event extras bug
  - Second one updates all glean_parser -generated code, these are mostly version string bumps

## Issue that this pull request solves

Closes: https://mozilla-hub.atlassian.net/browse/FXA-10169 and https://mozilla-hub.atlassian.net/browse/DENG-4405

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Other information (Optional)

Requires https://github.com/mozilla/glean_parser/pull/735 to land first.

### CODE REVIEW

**Comment by clouserw** [comment]
For reviewer: Note not all tests ran

**Comment by LZoog** [comment]
Hi @akkomar, thanks for taking a look at this and sorry for all the merge conflicts.

I have a question about [the Glean schema expecting events to be strings](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/main/schemas/glean/glean/glean.1.schema.json#L109-L118), thanks for the link:
```
...
"events": {
  "items": {
    "additionalProperties": false,
    "properties": {
      "category": {
        "type": "string"
      },
      "extra": {
        "additionalProperties": {
          "type": "string"
        },
        "propertyNames": {
          "maxLength": 40,
          "type": "string"
        },
        "type": "object"
      },
...
```

I could be misinterpreting this, but it seems all event _property_ names must be strings which makes sense since it's an object, but I'm not sure if this means that all of our _values_ need to also be strings given it simply says `type: object` and doesn't drill down into object values? 

I know your patch is focusing on those backend events, but some of those `third_party_auth` edits is an event extra for the front-end that we added recently. We're using the [this Boolean metric type](https://github.com/mozilla/glean.js/blob/eca7d5665be4f2e51ec43628c4427c9def35980b/glean/src/core/metrics/types/boolean.ts#L89) for the value of `event: { third_party_auth: true }` by [applying that here](https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/lib/glean/index.ts#L135-L136) and [the ticket](https://mozilla-hub.atlassian.net/browse/FXA-10119) for [that patch](https://github.com/mozilla/fxa/pull/17287/files) specifically requested a boolean. What's the proper way to use a basic boolean event if we can't use it for an event _property_ type?

If all of this must be strings, I think we need a tweak in that `populateMetrics` function and that we may need to further adjust the YAML to reflect there's no booleans (in this branch, if I search for "boolean" in `*.yaml`, I see 6 references to `boolean` and one to `labeled_boolean`), LMK if I can help. Thanks!

**Comment by chenba** [comment]
@akkomar there's a discrepancy in the supported types for event extras between frontend and backend Glean, correct? The docs mentioned boolean but that's frontend only?

**Review by chenba — APPROVED** [review]

**Comment by akkomar** [comment]
> I could be misinterpreting this, but it seems all event _property_ names must be strings which makes sense since it's an object, but I'm not sure if this means that all of our _values_ need to also be strings given it simply says `type: object` and doesn't drill down into object values? Or maybe it does with `additionalProperties`.

No, the values you set in the code do not to be strings. Per [Glean docs](https://mozilla.github.io/glean/book/reference/metrics/event.html#extra-metric-parameters), strings, booleans, and numbers are supported, but they are all converted to strings for transport. Docs seem to be unclear, we should improve this.
In the schema, `"additionalProperties": { "type": "string" }` defines types of the value in the extra object.


> I know your patch is focusing on those backend events, but some of those `third_party_auth` edits are around an event (...)
> If all of this must be strings, I think we need a tweak in that `populateMetrics` function to at least clean it up and that we may need to further adjust the YAML to reflect there's no booleans (...)

All seems fine to me, booleans are supported as extra types in Glean.js, with this change we are making backend telemetry behave in the same way.

> BTW, " which causes these pings to fail validation"... where does this validation happen? Can we check this on our side?

Validation happens in the ingestion Decoder (`*-logging.decoder` in [ingestion architecture diagram](https://mozilla.github.io/gcp-ingestion/architecture/overview/)). Data team monitors these errors regularly as part of [Platform Health Check](https://mozilla.cloud.looker.com/dashboards/387?Submission+Date=90+day+ago+for+90+day) and notifies other teams if needed. This particular error popped out in "Schema Errors" section as `#/events/0/extra/linking [accounts_backend.events_v1`.
Generally we do not expect you to check these type of errors, it's on us to see them and let team know if they need to fix something. Especially that in this case this was an error in Glean parser. Having said that if you wanted to check this from time to time on your own, drilling down to the schema errors chart ("Explore from here...") and filtering for `accounts-*` app id would be a good place to start. Let me know if more detailed instructions would be helpful.


> @akkomar there's a discrepancy in the supported types for event extras between frontend and backend Glean, correct? The docs mentioned boolean but that's frontend only?

No, we now should be at parity between frontend and backend wrt event extra types. What we do here for backend events is equivalent to how Glean.js handles them: [allowing string, boolean, and number in the API](https://github.com/mozilla/glean.js/blob/eca7d5665be4f2e51ec43628c4427c9def35980b/glean/src/core/metrics/events_database/recorded_event.ts#L13) and [converting values to strings for transport](https://github.com/mozilla/glean.js/blob/eca7d5665be4f2e51ec43628c4427c9def35980b/glean/src/core/metrics/events_database/recorded_event.ts#L158).

**Comment by chenba** [comment]
Closing this in favor of #17470. Thanks, @akkomar.

**Pull request closed without merging**
