### PR TITLE
fix(metrics): add geolocation to get-metrics-flow

### PR DESCRIPTION
**Pull request by irrationalagent**
Fixes https://github.com/mozilla/fxa/issues/1224

I couldn't actually test this locally bcs for the life of me I can't get fxa-email-service to build on `npm install`

<details>
  <summary>Click for example error msg i was seeing</summary>
`error: Could not compile `security-framework-sys`.
warning: build failed, waiting for other jobs to finish...
error: could not exec the linker `cc`
  |
  = note: Not a directory (os error 20)
  = note: "cc" "-m64" "-L" "/Users/loines/.rustup/toolchains/nightly-2018-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.0.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.1.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.10.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.11.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.12.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.13.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.14.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.15.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.2.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.3.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.4.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.5.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.6.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.7.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.8.rcgu.o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.build_script_build.cun14r2b-cgu.9.rcgu.o" "-o" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/build/core-foundation-sys-2c2efb62155710fc/build_script_build-2c2efb62155710fc.5g2ajhe5khvqws1c.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/loines/Documents/GitHub/fxa/packages/fxa-email-service/target/debug/deps" "-L" "/Users/loines/.rustup/toolchains/nightly-2018-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/loines/.rustup/toolchains/nightly-2018-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-9e5a69db4dc01737.rlib" "/Users/loines/.rustup/toolchains/nightly-2018-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-5a2cb5c752e3ae9c.rlib" "/Users/loines/.rustup/toolchains/nightly-2018-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-88ee0f866cc5107b.rlib" "/Users/loines/.rustup/toolchains/nightly-2018-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc_system-418f733d0e05a87c.rlib" "/Users/loines/.rustup/toolchains/nightly-2018-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-faa0a0baebb4269f.rlib" "/Users/loines/.rustup/toolchains/nightly-2018-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-c18bb86c34490d18.rlib" "/Users/loines/.rustup/toolchains/nightly-2018-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-291d1e3476ad529e.rlib" "/Users/loines/.rustup/toolchains/nightly-2018-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-d676450268a06e1b.rlib" "-lSystem" "-lresolv" "-lc" "-lm"
error: aborting due to previous error
error: Could not compile `core-foundation-sys`.
warning: build failed, waiting for other jobs to finish...
error: build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 101
npm ERR! fxa@2.0.0 postinstall: `_scripts/postinstall.sh`
npm ERR! Exit status 101
npm ERR! 
npm ERR! Failed at the fxa@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/loines/.npm/_logs/2019-05-23T19_41_29_164Z-debug.log
MacBook-Pro:fxa loines$ cc --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`
</details>

So if someone could check this branch to see if country is being added to the amplitude events, I would appreciate it (or if you know what's going on above lmk and I'll do it),  (edit) but iiuc what i did add to the tests *should* check for a country field in the amplitude event.

however I'm also not sure I'm modifying the tests correctly or if I need to add other things

### CODE REVIEW

**Comment by philbooth** [comment]
Hey @irrationalagent, I'm on PTO today but will have a look at this on Monday if nobody else beats me to it.

**Comment by philbooth** [comment]
@irrationalagent, arrgh, sorry to be a pain, we need all commits to be GPG-signed in this repo now. Can you follow the steps here and then re-apply the commit:

https://help.github.com/articles/about-gpg/

**Comment by irrationalagent** [comment]
sorry I've been ooo, I'll do the signing today

**Comment by irrationalagent** [comment]
k finally got signing to work, can't decipher why tests are failing now though, maybe just need to be re-run

**Comment by vladikoff** [comment]
> k finally got signing to work, can't decipher why tests are failing now though, maybe just need to be re-run

Restarted

**Comment by irrationalagent** [comment]
OK i think this good to go, what's the chance this could go out on monday? have I missed the boat there?

**Comment by philbooth** [comment]
> OK i think this good to go, what's the chance this could go out on monday? have I missed the boat there?

I was planning to retarget this PR at the `train-138` branch before merging but didn't get round to that last nigt. But actually it sounds like you need it in `train-137` anyway, so I can cherry-pick it there instead.

**Comment by philbooth** [comment]
> But actually it sounds like you need it in `train-137` anyway, so I can cherry-pick it there instead.

Ah, except 138 is already on stage. I'll copy it to 138 and hopefully there's no hold-ups.

**Pull request merged**
