### PR TITLE
fix(docs): rename sequence to flow in fxa-70

### PR DESCRIPTION
**Pull request by philbooth**
The way the term `sequence` is used in this feature description is a little bit jarring to me. Feel free to ignore this as bikeshedding / splitting hairs / my poor level of English comprehension.

I understand 'sequence' as meaning a specific order that items occur in, rather than an instance of that order which happened at a specific point in time. For example, if the sequence `2-4-6-8` has an id `1`, I expect all instances of that sequence to have the same sequence id, regardless of when they occurred (in this imaginary and arbitrary model that I just invented to try and prove a point :confused:).

In a chat with @rfk, I wondered whether the word `series` was better suited to uniquely identifying a set of events. He pointed out that the proper term would be `session` and also suggested `flow` as an alternative. It's since occurred to me that `journey` could be another one that has legs.

Opening this PR to propose a change and see if anyone else at all is even remotely bothered about it. Feel free to ignore / close.

### CODE REVIEW

**Comment by rfk** [comment]
The similar concept in google analytics is called "session":

  https://support.google.com/analytics/answer/2731565?hl=en

But that already means something pretty important and pretty different in FxA land so I don't think we can use it.

**Comment by rfk** [comment]
After sleeping on it, I prefer "flow" to "series" and we have some prior art for this term in our "flow analysis" dashboard, which contains broadly the sort of graphs that I want this feature to enable:

  https://metrics.services.mozilla.com/accounts-detail-dashboard/flow/

@philbooth is that less jarring than "sequence"?

**Comment by philbooth** [comment]
Yep, `flow` is better than `sequence` I reckon. Have updated the PR.

**Comment by rfk** [comment]
the bikeshed is painted, ship it! :-P

**Pull request merged**
