### PR TITLE
chore(release): Merge train 146 into master

### PR DESCRIPTION
**Pull request by shane-tomlinson**

### CODE REVIEW

**Comment by vbudhram** [comment]
It is a bit odd that this PR is failing even though the fixes are in the master branch. Wonder if something is caching going on?

**Comment by vladikoff** [comment]
@vbudhram was 

> Unfiltered advisories:
  https://npmjs.com/advisories/1164

Fixed?

**Comment by vbudhram** [comment]
> Fixed?

I thought so, running `npm audit --json | audit-filter --nsp-config=.nsprc --audit=-` in payments-server and support panel on master branch don't show any advisories for me.

**Comment by vbudhram** [comment]
Closing in favor of https://github.com/mozilla/fxa/pull/2678

**Pull request closed without merging**
