### PR TITLE
feat(copy): Replaces front-end references to Firefox Monitor with Mozilla Monitor

### PR DESCRIPTION
**Pull request by vpomerleau**
## Because

* Monitor is rebranding

## This pull request

* Update all references and l10n strings and terms from Firefox Monitor to Mozilla Monitor
* Update link to monitor's site

## Issue that this pull request solves

Closes: #FXA-9036

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

### CODE REVIEW

**Review by bcolsson — APPROVED** [review]
Overall, no issues with the change here.

Noting here (since we already had one scare) that if we delete these brand terms and strings with the terms, and there's a need to rollback or do a dot release - the translations will be removed once strings reach the l10n repo. 

In the case of fluent strings referencing terms or other strings, if a translation can't be found the ID will be displayed instead of text rolling back to English.

**Comment by vpomerleau** [comment]
@bcolsson That's a good callout. Perhaps we should add a temporary `ftl` file for the strings we're removing from production. That way the translations won't be lost and we can do periodic cleanups once strings have been phased out for a certain amount of time and safe from reversals... 🤔

**Comment by clouserw** [comment]
@bcolsson I thought pontoon has had translation memory for a long time which would recall old strings for localizers to see?

**Comment by vpomerleau** [comment]
@clouserw The name is a bit misleading. Translation memory matches existing similar strings with new strings to suggest translations, but it's not a backup for deleted strings.

**Comment by bcolsson** [comment]
> @bcolsson I thought pontoon has had translation memory for a long time which would recall old strings for localizers to see?

Like @vpomerleau said, the TM would allow them localizers to translate again with minimal effort. But Pontoon automatically removes deleted strings from files. If we decided we actually needed a string we already deleted and were to be add it back, it would be treated as a new string. So while it'd be minimal work for translators to add the strings back, it would have to go through the localization process. (So require a translator to look at and approve the string before it gets exposed.)

**Comment by clouserw** [comment]
Good to know.  I thought there would be some equivalent to obsolete strings in po files.  But anyway -- rolling back the code is a bunch of work for engineering too, so, we'll avoid it as much as we can.  I don't think we should optimize for it in this case (i.e. adding obsolete strings to a new ftl file).

**Review by chenba — APPROVED** [review]
The PR looks fine.  The client name in the oauth db is still "Firefox Monitor" though so I'm not sure if QA will see that somewhere.

**Comment by vpomerleau** [comment]
Thanks @chenba! db change was handled in another PR: https://mozilla-hub.atlassian.net/browse/FXA-8506 and there's a note in the deploy doc to flip that switch on Feb 6.

I'll add a note for QA so they know what to check and what not to worry about at this stage.

**Comment by vpomerleau** [comment]
@clouserw Would that change in the database show up in stage at the same time as this front-end change?

**Pull request merged**
