### PR TITLE
chore(payments): clean up subplat API code unused after SCA switch over

### LINKED ISSUE #5850: Remove dead subscription API routes and code from the server
After the client-side switches to using the new API methods for Payment and Setup Intents, the unused routes and code should be removed.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2229)
┆Issue Number: FXA-2229

### PR DESCRIPTION
**Pull request by lmorchard**
~Depends on PR #6341 landing first.~ Landed.

fixes #5850

### CODE REVIEW

**Comment by lmorchard** [comment]
Opening as a draft to see what CI does with this, first. Lots of code deleted and I only ran *most* of the tests locally.

**Comment by lmorchard** [comment]
Rebased against main and PR #6341

**Comment by lmorchard** [comment]
Finally see a green CI run after another rebase against main and several retries.

**Review by bbangert — APPROVED** [review]
All the server-side stuff looks good to me.

**Comment by lmorchard** [comment]
I don't think this PR should have been closed? Planning to merge after another review maybe

**Pull request merged**
