### PR TITLE
chore(ui): update default avatars

### LINKED ISSUE #1015: [Trailhead] Replace Default Avatars
We need the following assets: 
1. An SVG that shows up on the accounts and payments servers
2. PNGs that are stored on the profile servers

Requirements: 
1. Need to be circular images
2. They should not have any transparency inside the circle
3. PNGs need to be 100x100, 200x200, and 600x600

The PNGs are the things that get sent to different services (Firefox, Monitor, Send etc etc). the SVG is used locally on FxA.

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #1015

### CODE REVIEW

**Comment by johngruen** [comment]
note, i scaled up the PNGs a bit, b/c the current sizes seem arbitrary and don't look good on hidpi displays

**Comment by shane-tomlinson** [comment]
@johngruen - The size of those .png files has exploded!

### before

Screenshot 2019-05-09 at 21 09 06


### after

Screenshot 2019-05-09 at 21 09 21

The "small" image is now larger in KB than our previous large image. Can these be optimized?

**Comment by bbangert** [comment]
I ran default-profile.png through https://tinypng.com/ and it went from 16.9KB -> 9.5 KB. I can't see any difference. 

Here's the 9.5KB version:
default-profile(1)

Maybe it could get smaller yet if more lossy compression was applied?

**Comment by johngruen** [comment]
The current ones are also too small and show up pixelated (see the default avatar), so the sizes are bigger. additionally, the gradient is going to add a bit of size. Let me run them back through imageOptim and play around with my settings a bit

**Comment by johngruen** [comment]
also i take exception to "exploded"...i think "exploded" only starts at two orders of magnitude ;)

**Comment by johngruen** [comment]
I can get them down to 5/10/21 without lossy compression...does that work @shane-tomlinson ... FWIW, bumping sizes makes sense given uses like this (upsampling a 200x200 image to an effective 480x480):

Screen Shot 2019-05-10 at 11 59 48 AM

**Comment by johngruen** [comment]
Screen Shot 2019-05-10 at 12 07 40 PM

**Comment by johngruen** [comment]
woo!

**Pull request merged**
