### PR TITLE
use 2 columns for engines in cwts on mobile

### LINKED ISSUE #1201: Trailhead: CWTS continue button is below the fold on mobile
Look how far down that button is. There is no way that shows on the screen on mobile.

Screenshot 2019-05-22 at 12 04 50

Setting the Fx Dev tools to a Galaxy S9, here's what we see:

Screenshot 2019-05-22 at 12 06 30

This is going to lead to fewer people clicking "continue" on this screen on mobile.

cc @ryanfeeley, @davismtl

### PR DESCRIPTION
**Pull request by dannycoates**
closes #1201 

## Mobile
Screen Shot 2019-06-12 at 10 54 44 AM

## Desktop
Screen Shot 2019-06-12 at 10 55 12 AM

### CODE REVIEW

**Comment by ryanfeeley** [comment]
@dannycoates How are bookmarks in German?

**Comment by dannycoates** [comment]
Screen Shot 2019-06-12 at 11 17 13 AM

**Comment by ryanfeeley** [comment]
@dannycoates I mean howdoesitwork withlongwords thatwrap tothesecond line?

**Comment by dannycoates** [comment]
Screen Shot 2019-06-12 at 3 40 14 PM

**Comment by SorinaFlorean** [comment]
Verified as fixed on Win10. 
On mobile, there are some changes to about:config in order to trigger the new UI? On iOS we got the two columns but not the new UI (and we don't have about:config). @dannycoates

**Comment by vbudhram** [comment]
@SorinaFlorean You should be able to use the instructions from https://github.com/mozilla/fxa/issues/1306#issuecomment-506757160 to configure Firefox iOS to use the stage environment. If you create the account on iOS you should see the CWTS page.

**Comment by SorinaFlorean** [comment]
@vbudhram we needed to add also **style=trailhead** to the URL link, but we didn't found in docs the new pref. 
Verified as fixed on stage server - Train 140.

**Pull request merged**
