### PR TITLE
Train 151

### PR DESCRIPTION
**Pull request by 6a68**
Merging 151.2 into master. Not sure what to make of the test conflicts, comments welcome.

### CODE REVIEW

**Comment by 6a68** [comment]
Looks like the tests failed with a mozinstall error. Retrying...

**Comment by vbudhram** [comment]
@6a68 Test conflicts are most likely from a recently landed issue in master. Looks like this isn't documented, but typically we create a merge branch (train 151 and master) and resolve conflicts there, then merge that into master.

**Comment by shane-tomlinson** [comment]
> packages/fxa-content-server/tests/functional/fx_browser_relier.js 

@6a68 - GASP! We have a merge conflict!

**Comment by 6a68** [comment]
Closing in favor of https://github.com/mozilla/fxa/pull/3612

**Pull request closed without merging**
