### PR TITLE
fix(fxa-settings): remove horizontal margin for resend verification code

### PR DESCRIPTION
**Pull request by dhruva248**
## Because

-

## This pull request

-

## Issue that this pull request solves

Closes: # (7724)

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

### CODE REVIEW

**Review by jodyheavener — CHANGES_REQUESTED** [review]
@dhruva248 Thanks for this, it looks good! Before we can merge you'll need to enable [GPG signing](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key) for your commits.

**Comment by dhruva248** [comment]
> @dhruva248 Thanks for this, it looks good! Before we can merge you'll need to enable [GPG signing](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key) for your commits.

@jodyheavener consider it done!

**Comment by meandavejustice** [comment]
@dhruva248 Here is a blog post with some steps for gpg signing commits, https://micropipes.com/blog/2016/08/31/signing-your-commits-on-github-with-a-gpg-key/

**Comment by dhruva248** [comment]
> @dhruva248 Thanks for the contribution. Here is a blog post with some steps for gpg signing commits, https://micropipes.com/blog/2016/08/31/signing-your-commits-on-github-with-a-gpg-key/

 I checked it out, thanks a lot :)

**Review by jodyheavener — APPROVED** [review]
Awesome thanks @dhruva248!

**Pull request merged**
