### PR TITLE
fix(links): stop converting links to text on Firefox iOS

### LINKED ISSUE #3047: Firefox iOS: Enable SUMO/help links
#  Description

On Firefox iOS, we now open a secondary webview to enable showing help links: https://github.com/mozilla-mobile/firefox-ios/pull/5639

If the class`visible-url` is removed from help links, they will open in an overlay webview as they already have `target=_blank`. The target attribute must not be removed of course, we need them to open in a new window. 

### Steps to reproduce

Currently, help links are displayed in full and are not tappable.

### Expected result

Tapping help links triggers target=_blank behaviour and opens them in an overlay webview. Pressing back on the overlay webview closes it and returns the user to the FxA webview.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3047

### CODE REVIEW

**Comment by garvankeeley** [comment]
You are too fast! Should we try to align this somewhat with the release of v21 (~Dec 3rd)? That is when Firefox iOS will be able to handle these links.

**Comment by vladikoff** [comment]
@garvankeeley ok we should be able to determine which train will deploy after Dec 3

**Comment by vladikoff** [comment]
@clouserw could we schedule this to be part of a `> Dec 3` train?

**Comment by bbangert** [comment]
Just a note that a rebase is now needed for this.

**Comment by clouserw** [comment]
@vladikoff please rebase this and then we're ready to land it.  Thank you

**Comment by vladikoff** [comment]
Rebased! We should merge this for 151 at some point, maybe once 150 won't be needing anymore point releases

**Pull request merged**
