### PR TITLE
fix(email): update refresh recovery codes link in email

### LINKED ISSUE #8024: [FxA-Settings] "Generate codes" button from email opens a blank Settings page
**Build**
Stage [Train 1.203.2]

**Affected platforms**
Windows 10

**Prerequisites:**

* the user has the 2FA enabled and the recovery codes saved

**Steps to reproduce**

1. Launch Firefox and follow the login steps (enter valid email and password credentials)
1. Click on "Trouble entering code?" link.
1. Copy and paste the 10-digit code from the saved list and click on the "Verify" button.
1. Log out.
1. Repeat Step 1->3 until 2 recovery codes remain unused.
1. Check the email inbox.
1. Click on "Generate codes" button from '2(1) recovery code(s) remaining' email

**Expected results**
The user is redirected to generate new recovery codes.

**Actual Results**
Blank Settings page is displayed - [page url](https://accounts.stage.mozaws.net/settings/two_step_authentication/recovery_codes?low_recovery_codes=true&email=vtamas%2B223%40mozilla.com&uid=da261b2d38d64eef9b7bf715a561e18e&utm_medium=email&utm_campaign=fx-low-recovery-codes&utm_content=fx-recovery-codes).

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3285)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15704/Screenshot_31.png">Screenshot_31.png</a>
┆Issue Number: FXA-3285

### PR DESCRIPTION
**Pull request by dannycoates**
to the new settings route

fixes #8024

### CODE REVIEW

**Comment by dannycoates** [comment]
funny enough I wrote a functional test for this... in playwright https://github.com/mozilla/fxa/commit/3e5b90ac0e321f7fb3530d9f2ab8a3632856f38f#diff-b5a7865e42d3819056593608bbbaa13edb24ace228223f444637d753f99f0c7d

**Review by vbudhram — COMMENTED** [review]
@dannycoates This does work as described, however I think one issue was that it automatically generates new codes when you goto the page (and nukes your old codes). I think this could be surprising to a user.

In old settings, there was a confirmation dialog before performing the replacement. Thoughts on adding this? Or maybe not a huge issue?

**Comment by dannycoates** [comment]
> I think this could be surprising to a user.

🤷‍♂️ the button in the email literally says "Generate codes". I guess we could parse the querystring to see if it came from an email link and show a modal, but i don't have a preference either way.

**Comment by vbudhram** [comment]
> I guess we could parse the querystring to see if it came from an email link and show a modal, but i don't have a preference either way

If it doesn't add too much complexity we could probably add it, otw lets go with what you have.

**Review by vbudhram — APPROVED** [review]
@dannycoates 👍🏽

**Pull request merged**
