### PR TITLE
feat(fxa-auth-server): Adds recording when the device was last seen in push

### PR DESCRIPTION
**Pull request by tarikeshaq**
## Because

- We have a hypothesis that a large number of push failures are attributed to devices that never sign in again.

## This pull request

- Adds Statsd field that reports when that device was last seen

## Issue that this pull request solves

Closes: https://mozilla-hub.atlassian.net/browse/FXA-7066

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

**Comment by tarikeshaq** [comment]
Created https://mozilla-hub.atlassian.net/browse/FXA-7066 with more context on what I'm doing here, happy to change course if we think there is a better approach!

**Review by vbudhram — APPROVED** [review]
@tarikeshaq This LGTM, we don't need a data review for this.

**Comment by tarikeshaq** [comment]
Thanks @vbudhram!! I imagine we need someone from the team to re-create the PR to get it landed? Happy to help in any way if there are any remaining questions

**Comment by vbudhram** [comment]
@tarikeshaq Nope, those test failures are unrelated, thanks for the PR!

**Pull request merged**
