### PR TITLE
feat(fxa-57): add overview

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by vladikoff** [comment]
@vbudhram r?

**Comment by vbudhram** [comment]
A couple of notes/questions
* In diagram, `Adding Reminders`, what would happen if the user verifies their account before the 48hrs? Diagram seems to imply that the reminder entry rows are added when the account is created. If a user verifies the account, I am guessing the reminder rows are removed?
* When does the process for `fetching valid reminders entries` query kick off?

**Comment by vladikoff** [comment]
> what would happen if the user verifies their account before the 48hrs? Diagram seems to imply that the reminder entry rows are added when the account is created. If a user verifies the account, I am guessing the reminder rows are removed?

Hm maybe we should add this: `If a user verifies the account, I am guessing the reminder rows are removed`. This means adding deletion logic to the fxa-auth-server 

> When does the process for fetching valid reminders entries query kick off?

the fxa-auth-mailer polls and fetches the reminders after it stats.

**Comment by vladikoff** [comment]
@vbudhram updated with notes and a new digram.

**Comment by vbudhram** [comment]
Diagram looks good. I did have one more question, are both email reminders created in table at same time?

**Comment by vladikoff** [comment]
> Diagram looks good. I did have one more question, are both email reminders created in table at same time?

Yeap, this simplifies the logic a bit on the mailer. Also allows to easily add / remove the number of  reminders

**Comment by vladikoff** [comment]
@rfk if you have a sec to glance at this so we are all on the same page :page_facing_up:

**Comment by rfk** [comment]
Looks good.  It may be worth doing "mark account as verified" and "delete pending verification reminders" in a single transaction in auth-db-mysql, rather than having auth-server make a separate request to delete the reminders.  Or alternately, deleting the reminders *before* marking the account as verified, on the theory that it's better not to send a reminder than to send one that's unnecessary.

**Comment by vladikoff** [comment]
> Or alternately, deleting the reminders before marking the account as verified, on the theory that it's better not to send a reminder than to send one that's unnecessary.

:+1:

**Comment by vladikoff** [comment]
Thanks for all the questions and feedback, I converted your questions into notes in the spec and made updates.

**Pull request merged**
