### PR TITLE
task(ci): Add compile CI job to catch TS errors

### PR DESCRIPTION
**Pull request by dschom**
Because:
- TypeScript errors were occurring during the docker build of the deploy workflow
- We want to catch typescript errors as early as possible

This Commit:
- Updates work spaces using TS to support a compile target that runs `tsc --noEmit`
- Adds a compile job to the ci pipeline that invokes the `compile` script across all workspaces

## Because

- TypeScript errors were occurring during the docker build of the deploy workflow
- We want to catch typescript errors as early as possible

## This pull request

- Runs tsc and linting operations
- Adds compile job

## Issue that this pull request solves

Closes: FXA-7057

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

### CODE REVIEW

**Comment by chenba** [comment]
We can remove https://github.com/mozilla/fxa/blob/main/_scripts/compile-backend-ts-services.sh then?

**Comment by dschom** [comment]
> We can remove https://github.com/mozilla/fxa/blob/main/_scripts/compile-backend-ts-services.sh then?

@chenba Unfortunately these are still needed at the moment. This script only builds downstream deps and these must be built first. Their outputs are stored to the workspace and then used by other tests. Also the compile job runs in parallel with other tests, and uses `tsc --noEmit` so no artifacts are created but the operations are faster. I think as we move forwards with esbuild, this is a nice middle ground to ensure type safety and maintain decent performance for jobs that are running through esbuild.

**Comment by chenba** [comment]
Love the idea but this is breaking CI at the moment so we're going to revert it.

**Comment by biancadanforth** [comment]
> > We can remove https://github.com/mozilla/fxa/blob/main/_scripts/compile-backend-ts-services.sh then?
> 
> @chenba Unfortunately these builds are still needed at the moment. This script only builds downstream deps and these must be built first. Their outputs are stored to the workspace and then used by other tests. Also the compile job runs in parallel with other tests, and uses `tsc --noEmit` so no artifacts are created but the operations are faster. I think as we move forwards with esbuild, this is a nice middle ground to ensure type safety and maintain decent performance for jobs that are running through esbuild.

I knew this sounded familiar -- https://mozilla-hub.atlassian.net/browse/FXA-5063 is where I added the `compile-backend-ts-services.sh`. At the time, I [noted](https://mozilla-hub.atlassian.net/browse/FXA-5063?focusedCommentId=556041):
>  For front-end packages, tsc --build will not "just work", as the .tsx files must first be compiled to TS before being passed in. This is part of what the rescripts command in the yarn build of our React front-end packages does IIUC.
> * E.g. running tsc --build on fxa-payments-server will return 87 erroneous TS errors from these .tsx files while yarn build runs successfully.

So I think we will need to do some intermediary step before compiling front-end packages?

**Pull request merged**
