### PR TITLE
task(CI): Enable Glean probe-scraper task

### PR DESCRIPTION
**Pull request by badboy**
## Because

[Enabling the new app in probe-scraper](https://bugzilla.mozilla.org/show_bug.cgi?id=1830504).
[The PR has been merged](https://github.com/mozilla/probe-scraper/pull/589)

## This pull request

-

## Issue that this pull request solves

Closes: # (issue number)

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

### CODE REVIEW

**Comment by badboy** [comment]
Ah yes, the task already run on this and failed.
That should be fixed with the next deploy (tomorrow). We should hold off until then anyway, I'll check in tomorrow.

**Review by chenba — APPROVED** [review]
👍  And thank you!

**Comment by chenba** [comment]
@badboy oh it's not liking the commit because it's not signed.

**Comment by chenba** [comment]
Closing in favor of https://github.com/mozilla/fxa/pull/15390

**Pull request closed without merging**
