### PR TITLE
feat(fido2): Add fido2 Support FXA

### LINKED ISSUE #5548: Create a util.js for fido2 server (server side)
**(Phase-1 - Server): This will serve as base util lib for our server fido2**

- Use `cbor` and `crypto` lib
- Function to convert public key to an OpenSSL-compatible PEM text format
- CosePublicKey conversion to raw PKCS ECDHA key
- VerifySignature function

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2033)
┆Issue Number: FXA-2033

### PR DESCRIPTION
**Pull request by imskr**
Fixes #5548

### CODE REVIEW

**Comment by dannycoates** [comment]
please remove the `package-lock.json`. the top level `yarn.lock` covers all of our packages

**Comment by imskr** [comment]
Cool. Thank you @dannycoates

**Comment by imskr** [comment]
@dannycoates why its showing error in content server-2

**Comment by imskr** [comment]
Fixes #5579

**Comment by imskr** [comment]
@vbudhram Closing this! Messed up my branch.

**Pull request closed without merging**
