### PR TITLE
chore(fxa-react): update jest and storybook to support CRA-style importing SVGs as a component

### PR DESCRIPTION
**Pull request by jodyheavener**
r? @LZoog 

Also sneaks in compiling Tailwind with _all_ fxa-react components

### CODE REVIEW

**Comment by jodyheavener** [comment]
@lmorchard can you see why this would be breaking Storybook deploys?

**Comment by lmorchard** [comment]
>  Looks related to not inputting a PW?

I *did* just reset an access token in CircleCI, so this might have bad lucked into my process of doing that. Just did a restart in CI to see if that's the case

**Comment by jodyheavener** [comment]
I think this might be an issue on my end now. Checking.

**Comment by FxaStorybooks** [comment]
# Storybook Deployment
Pull Request: https://mozilla-fxa.github.io/storybooks/pulls/5480/
Commit: https://mozilla-fxa.github.io/storybooks/commits/be8d6dda5ff41e36cfd33830dddfbb6aaeaba09d/

**Comment by lmorchard** [comment]
Looks like a rerun did it ^

**Comment by jodyheavener** [comment]
Oh wow. That is odd.

**Comment by jodyheavener** [comment]
Thank you!

**Comment by lmorchard** [comment]
Well, I broke it, so uhh you're welcome! 😅

**Pull request merged**
