### PR TITLE
docs(db): update root README on how to connect to local FxA MySQL DBs

### PR DESCRIPTION
**Pull request by biancadanforth**
Because:

* We should document the basic process for new contributors.

This commit:

* Adds a new "Connecting to a local MySQL DB" section to the root project README.

Closes #No issue

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

**Comment by dannycoates** [comment]
Another method is if you have the mysql-client installed locally, (mine is in `/usr/local/opt/mysql-client/bin` via `brew install mysql-client`):

```
/usr/local/opt/mysql-client/bin/mysql -uroot --host=127.0.0.1 --port=3306
```

**Comment by dannycoates** [comment]
as a one-liner we could put it in the root package.json scripts section

**Comment by biancadanforth** [comment]
> Could combine those steps into `docker exec -it "$(docker container ls | grep mysql | cut -d' ' -f1)" mysql`

I thought about merging it all into one command, but I also wondered if that might be a little confusing for newer contributors. I'll merge it just to keep the section a little shorter.

**Comment by biancadanforth** [comment]
> as a one-liner we could put it in the root package.json scripts section

Unfortunately with all the quotes in the command and the fact that the npm run script has to be wrapped in a set of quotes, I don't think it will work -- I'm getting:

```sh
bdanforth ~/Projects/fxa (update-readme-mysql-db) $ yarn run mysql
Error: No such container: $(docker container ls | grep mysql | cut -d
```

**Pull request merged**
