### PR TITLE
feat(fxa-57): add sqs outline

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by vladikoff** [comment]
@philbooth r? Let me know if anything is confusing in the LucidChart provided.

**Comment by vladikoff** [comment]
cc @dannycoates, any feedback on this?

**Comment by philbooth** [comment]
Sorry for not getting round to this last week @vladikoff.

It looks good to me, I just have two questions about things I don't quite understand from the diagram.

1. After step `3`, if the answer is "no", the message is delayed for 12 hours. Is that because there is no way to delay the message for the correct (48/168) number of hours in the first place, or is it because of something else like reliability of the timer/queue?

2. At step `7` it says to queue up the second email "if needed". Is that essentially the same as saying to queue up the second email if we've sent the first email? Or is it checking the verification state again?

**Comment by vladikoff** [comment]
> After step 3, if the answer is "no", the message is delayed for 12 hours. Is that because there is no way to delay the message for the correct (48/168) number of hours in the first place, or is it because of something else like reliability of the timer/queue?

Max delay is 12 hours yeah

> At step 7 it says to queue up the second email "if needed". Is that essentially the same as saying to queue up the second email if we've sent the first email? Or is it checking the verification state again?

Hm I'll try to clarify in the diagram. If account is not verified then we send the first email, delete the queue item for the first email. Then queue up the second email. 

If account was verified then we just delete the queue item for the first email and never send anything and do not queue anything new.

**Comment by vbudhram** [comment]
@vladikoff I wasn't tagged for review on this but did have a comment. Noticed that diagram starts at account creation, will this only affect new users? Would we want to have a something that does verification reminder for existing users?

**Comment by vladikoff** [comment]
>  will this only affect new users?  

Yeap, existing users are out of scope for this one.

**Comment by rfk** [comment]
Since we decided SQS is not a great fit for this, should we just close out this PR, or replace it with something else?

**Comment by vladikoff** [comment]
Sure!

**Pull request closed without merging**
