### PR TITLE
chore(style):  Remove unused images in `fxa-content-server/app/images`

### PR DESCRIPTION
**Pull request by krtb**
Remove the following image files, from folder located in path, `fxa-content-server/app/images`
- `graphic_mail.png`
- `graphic_mail@2x.png`
- `account-verified.png`
- all files that start with `ddarrow`

Fixes issue [#2554](https://github.com/mozilla/fxa/issues/2554)
May overlap with issue [#1878](https://github.com/mozilla/fxa/issues/1878)

### CODE REVIEW

**Comment by LZoog** [comment]
Hey @krtb, thank you for this! Your PR title looks great - would it be possible to get you to make sure your commits are [GPG signed](https://help.github.com/en/articles/managing-commit-signature-verification)? This'll give you a fancy checkmark along with "Verified" text next to your commits (we require this to ensure the commits come from a trusted source).

Additionally, can I ask you to combine all of your commits into one, following the format of your PR title? After you're GPG signed, the easiest method IMO is to:
1. Run `git pull upstream master` (`upstream` referring to this repository, if you set the remote name to something else you will of course refer to that)
2. Run `git rebase -i upstream/master`
3. Place an `r` in front of the first commit, for `reword`, and an `s` in front of the other two, for `squash`
4. It'll ask you for your reworded commit - delete the first commit text, paste your PR title, and exit (`esc` then `:x` then `enter`)
5. Do a `git push -f origin remove-unused-images`

Comment here if you need help.

**Comment by krtb** [comment]
@LZoog, I did some digging into how to do a rebase and believed I pulled it off correctly, but I don't understand why there are 12 other commits and some conflicts. Is there another approach I should take?

**Comment by dannycoates** [comment]
@krtb it looks like something went weird with a rebase. Here's one possible way to fix it. Try pulling from fxa again then merge our master branch into yours, it should be a fast-forward. Then, from master, do a `git cherry-pick 43f980009b67b52fafbcf67c26cacbb28f20e54a` if that works then you can either delete your `remove-unused-images` branch and recreate it or use `git reset` to make it point to the same commit as master. Then force push that branch and it should show up here with one commit.

**Comment by krtb** [comment]
Hi @dannycoates, thanks for the help

I did a `git pull` and `git fetch --all`, I switched to my branch and merged with master.
After typing the cherry pick command I got 

```bash
On branch remove-unused-images
Your branch is ahead of 'origin/remove-unused-images' by 22 commits.
  (use "git push" to publish your local commits)

You are currently cherry-picking commit 43f980009.

nothing to commit, working tree clean
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
```

Should I continue with `git commit --allow-empty`?

**Comment by 6a68** [comment]
Hey @krtb, maybe try a fresh copy of the master branch, and then cherry-pick your commit on top of that.

**Comment by krtb** [comment]
The cherry picked worked from master! My apologies for not catching that. When I delete my old branch and create a new one from master, would it be best to rename it to `chore(style): Remove unused images in `fxa-content-server/app/images`? Or does that not matter now that I've gone through the other steps?

**Comment by LZoog** [comment]
@krtb When you say "it," do you mean the branch name? That can be whatever you like, but it would be ideal if in your PR into master, the only commit showing will merge is one with that commit message. :)

**Comment by krtb** [comment]
I force pushed from my new branch but it came in as a new PR, [krtb/Remove-unused-images-in-fxa-content-server/app/images](https://github.com/mozilla/fxa/pull/2862). Should I close this one?

**Comment by LZoog** [comment]
@krtb yeah, let's close this one in favor of that one. Thanks for sticking with this and seeing it through! I'll approve/merge your PR once Circle CI finishes its thing.

**Comment by krtb** [comment]
Thanks everyone for all the help! @LZoog, just wanted to say I love everything about Mozilla, and I have a deep respect all of the developers making the internet a better place. Whenever I get the chance, I recommend the Firefox browser and it's real respect for data privacy. Thank you for all your work!

**Pull request closed without merging**
