### PR TITLE
fix(speed-trap): replace `function` with `=>`

### PR DESCRIPTION
**Pull request by ionathanch**
## Because:
* `this` @ line 76 in `diffL1` in `diff` may be undefined rather than the class instance object since `diffL1` is a `function`.

## This pull request
* Replaces `function diffL{1,2} ()` with `const diffL{1, 2} = () =>`.

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

### CODE REVIEW

**Comment by ionathanch** [comment]
CircleCI is failing bc the config checks out

**Comment by clouserw** [comment]
Try rebasing / retriggering.  We fixed the broken image

**Comment by ionathanch** [comment]
I think it's just that it doesn't work when the PR comes from a different repo. Like it's the same problem blocking #14708

**Comment by clouserw** [comment]
This isn't failing in the way I would expect for that though.  @dschom this seems to have the same problem with checking out the tree

**Comment by vpomerleau** [comment]
@clouserw looks like this PR might need approval before tests can run? (first time contributor)
image

**Comment by clouserw** [comment]
I hit the button but I don't think that blocks circleci stuff.  Just github

**Comment by dschom** [comment]
@ionathanch Concerning the checkout, this is a case that wasn't considered. Also your PR looks good to me. Thank you for this patch! Do you mind if I just grab a patch and apply it myself? That would be the quickest way to get the fix in place. 

@clouserw The issue is like @ionathanch indicates. The checkout command (which was recently optimized to make startup times quicker) assumes the commit being tested lives in the main fxa repo. This commit doesn't, so git fails when the commit hash can't be located. 

I don't want to lose the gains from having the repo already primed in ci image, but we could put in some conditional logic for this sort of thing.

**Comment by clouserw** [comment]
Thanks for the info.  Doesn't sound like a high priority.  

I agree, I think best thing here would be to grab the patch with @ionathanch as author, you as committer and open a new PR.  

Thanks for the patch @ionathanch

**Pull request closed without merging**
