### PR TITLE
Revert "test(functional): remove old functional (only) intern tests and files"

### PR DESCRIPTION
**Pull request by chenba**
Looks like we still need packages/fxa-content-server/tests/intern.js for content-server tests.

### CODE REVIEW

**Review by vbudhram — COMMENTED** [review]
@chenba Maybe something I am missing, tests are passing in main?

**Comment by chenba** [comment]
> @chenba Maybe something I am missing, tests are passing in main?

I'll set this PR back to draft until we talk about https://mozilla-hub.atlassian.net/browse/FXA-8492 in triage.  But the quickest way to see an error is running `nx run fxa-content-server:test`.

**Comment by ashrivastava-qa** [comment]
@chenba are you still working on this? The [Jira ticket](https://mozilla-hub.atlassian.net/browse/FXA-8492) for this is currently assigned to me. Do you want me to assign that to you?

**Comment by chenba** [comment]
> @chenba are you still working on this?

I'm not working on it.  Thanks for checking.

**Pull request closed without merging**
