### PR TITLE
task(ci): update funcitonal test executor

### PR DESCRIPTION
**Pull request by dschom**
## Because

- To keep up with the latest version and new updates, upgrading the Playwright version to the latest 1.43.1.

## This pull request

- Updates the functional-test-runner images
- Upgrades Playwright version to 1.43.1

## Issue that this pull request solves

Closes: FXA-9135 FXA-9358

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Typically we do this for node versions, but it should also work for playwright versions. See docs here: https://mozilla.github.io/ecosystem-platform/how-tos/ci-guidelines#updating-ci-runner-images

### CODE REVIEW

**Comment by pdehaan** [comment]
```
Starting container mozilla/fxa-circleci:ci-builder-v3
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image cache not found on this host, downloading mozilla/fxa-circleci:ci-builder-v3

Error response from daemon: manifest for mozilla/fxa-circleci:ci-builder-v3 not found: manifest unknown: manifest unknown
```

**Comment by ashrivastava-qa** [comment]
@pdehaan Yes I see the error too and I am not sure how to resolve it. Dan is out on PTO as well. I might need to post this on the channel for help.

**Comment by ashrivastava-qa** [comment]
Okay looks like the changes I made worked for this PR. :) 
I am closing the [PR](https://github.com/mozilla/fxa/pull/16767) I opened for the Playwright upgrade and moving forward with this one as @dschom has rebased my branch on this one.

**Review by ashrivastava-qa — APPROVED** [review]
LGTM :)
Thanks @dschom!

**Pull request merged**
