### PR TITLE
Merge train-134 into master

### PR DESCRIPTION
**Pull request by philbooth**
This is the first tag cut from the monorepo. It's not something we have to deploy, but it serves as proof that the train-cutting scripts are working end-to-end with CI, DockerHub and so on.

On that note, there is one fix I had to apply to make Circle build the Docker images, just tweaking the filters in the `deploy-tag` workflow: 8359993. It's the minimal change I found that would make the jobs run.

With that fix and the application of a uniform tag and version string, merging this PR will serve to make future tags easy by running the in-tree release script (although we also need to make sure that #730 gets merged before we run it for real).

You'll see that all the services have the same version number now, and that it's `1.134.2`. Why `.2`? Because the customs server had already used `.1` and we need them all to share the same version string going forward.

Note there is also an equivalent PR in the private repo to apply the same changes there.

@mozilla/fxa-devs r?

### CODE REVIEW

**Comment by dannycoates** [comment]
It looks like`deploy-tag` is running on every push. I'm pretty sure we do want to filter out branches, which is how we [do it on Send](https://github.com/mozilla/send/blob/master/circle.yml#L127-L131). There only a tag triggers `build_and_deploy_stage`.

**Comment by philbooth** [comment]
> It looks like`deploy-tag` is running on every push. I'm pretty sure we do want to filter out branches, which is how we [do it on Send](https://github.com/mozilla/send/blob/master/circle.yml#L127-L131). There only a tag triggers `build_and_deploy_stage`.

Feel free to make whatever changes you think are appropriate, I'm not at all wedded to this approach.

Fwiw I only did it this way because `.circleci/deploy.sh` already contains logic for checking the tag/branch name, so `deploy-tag` looks like it's a NOP for other builds?

(that's how it used to be set up for the old repos too, so I assumed the same here)

Sorry for messing it up!

**Comment by philbooth** [comment]
(sorry, just in case last message wasn't clear: when I had that branch filter in place, I wasn't seeing any of the deploy steps show up in the workflows, even with the other changes to add the tag filter in each job)

**Comment by philbooth** [comment]
Also, one more note, if you're testing changes out, note that you might notice weirdness in the changelogs if you don't have #730 applied. It's harmless if all you're doing is testing out tags, but wanted to mention in case you notice it a think hmmm...

**Comment by dannycoates** [comment]
Well, I screwed it up originally so, nbd. I'll look through the previous circle builds. maybe `modules-to-test.js` needs to change.

**Pull request merged**
