### PR TITLE
Train 169

### PR DESCRIPTION
**Pull request by vbudhram**
This needs to get onto train 170 and master...

### CODE REVIEW

**Comment by chenba** [comment]
@vbudhram Merge conflicts ☝️

**Comment by bbangert** [comment]
This will require a new 170 tag as well, right?

**Comment by vbudhram** [comment]
Yea, will need to go onto 170, I'm afk but can resolve conflicts after I get back.

**Comment by vbudhram** [comment]
Closing in favor of https://github.com/mozilla/fxa/pull/5269

**Pull request closed without merging**
