### PR TITLE
refactor(tests): Remove teamcity scripts

### PR DESCRIPTION
**Pull request by clouserw**
Because:

* We no longer use teamcity

This commit:

* Removes all the teamcity scripts

r? @jbuck and @ashrivastava-qa in case I'm wrong

### CODE REVIEW

**Review by vbudhram — APPROVED** [review]
@clouserw Nice find, we haven't used Team city in forever.

**Review by jbuck — APPROVED** [review]
🫡

**Review by ashrivastava-qa — APPROVED** [review]
LGTM! Thanks for taking care of this, @clouserw.

**Comment by clouserw** [comment]
Uhhh..... I merged this code but the PR didn't close.  A github hiccup I guess.  Closing...

**Pull request closed without merging**
