### PR TITLE
feat(fxa-72): Add outcomes to FxA-72 feature card

### LINKED ISSUE #145: Close out FxA-72: password reset ux
Including taking a fresh snapshot of the quantitative metrics from datadog, and noting any qualitative increase in quality of the password reset experience.

### PR DESCRIPTION
**Pull request by rfk**
Closes #145; @vbudhram r?

### CODE REVIEW

**Comment by vbudhram** [comment]
@rfk Spoke with @ryanfeeley and had some more notes/comes from this feature.

April 28 - May 5, 39% drop off after seeing the warning
April 21 - April 28, 34% drop off after seeing the warning
April 14 - April 21, 31% drop off after seeing the warning
April 7- April 14,  30% drop off after seeing the warning
March 31- April 7, 40% drop off after seeing the warning
March 24 - March 31, 39% drop off after seeing the warning
March 17 - March 24, 37% drop off after seeing the warning
March 10 - March 17, 32% drop off after seeing the warning
Jan 14 - Jan 21, 33% drop off after seeing

Not sure if this has a strong correlation for the success of the feature though.

**Comment by rfk** [comment]
@vbudhram worth adding a screenshot of this graph to the report for completeness?

**Comment by vbudhram** [comment]
@rfk Added the updated graph and a little blurb about it. r?

**Comment by rfk** [comment]
👍

**Pull request merged**
