### PR TITLE
Add initial description for FxA-79: mailcheck part two

### PR DESCRIPTION
**Pull request by rfk**
This proposes a concrete feature card for @ryanfeeley's "mailcheck part two" experiment, merging three outstanding issues into a larger feature so that we can prioritize it during product planning:

* https://github.com/mozilla/fxa-content-server/issues/3400
* https://github.com/mozilla/fxa-content-server/issues/3401
* https://github.com/mozilla/fxa-content-server/issues/3430

@ryanfeeley have I correctly captured your intention here?

### CODE REVIEW

**Comment by ryanfeeley** [comment]
:+1:

**Comment by ryanfeeley** [comment]
@rfk Looking at the A/B experiments, the old design had really zero impact at all. I think we've known that for a while, and given our very high invalid email rate, I figured that this feature would rank more highly in the backlog. @davismtl what do you think? Should we still do this or work on a version that auto-completes domain after the @ is typed.

For example:

ryanfeeley@
- gmail.com
- hotmail.com
- yahoo.com

ryanfeeley@g
- gmail.com
- gmx.de
etc.

**Comment by rfk** [comment]
ISTM this is small enough that we could still try it, assuming @davismtl gives the OK to prioritize it.

**Comment by davismtl** [comment]
This looks like a great quick fix. It might also help our mail deliverability by avoiding us from emailing invalid addresses.

**Comment by rfk** [comment]
@davismtl @ryanfeeley I'm going to be PTO shortly and won't have bandwidth to wrangle this, if you're interested can you guys please coordinate to get the feature card for this into "accepted" or similar in the features waffleboard?  I don't recall if we have an existing card or need to create a new one.

**Pull request merged**
