### PR TITLE
task(auth): Support v2 authPW in auth server

### PR DESCRIPTION
**Pull request by dschom**
## Because

- We are preparing to change some parameters for the client side key stretching
- We want to support legacy clients that rely directly on our API

## This pull request

- Sets up server side changes needed to support changes to client side key stretch
- Sets up server side changes needed to support changes to client side salt
- Adds some test coverage to ensure changes work for both old and new key stretch and salt
- Updates accounts table told hold two distinct password version
- Updates stored procedures accordingly

## Issue that this pull request solves

Closes: FXA-8719

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Other information (Optional)

This is a second pass on https://github.com/mozilla/fxa/pull/16189. It is just the `auth-server` component, and also ensures the API changes are backwards compatible, and non breaking.

### CODE REVIEW

**Comment by chenba** [comment]
Maybe I'm not reading carefully enough or something, but with this PR users would end up with two `kB`s?

**Comment by chenba** [comment]
@dschom Sorry about my short comment.  My concern is around two different `kB` _values_.  That's what the patch is doing when it generates two `wrapWrapKb`s.

Two wrapWrapKb db columns are necessary if we want to support two versions of key stretching simultaneously.  I just didn't understand how we are ensuring that they unwrap to the same kB value.

**Comment by dschom** [comment]
@chenba Without seeing the client side changes, this wouldn't really be clear. That is the downside of breaking this into a server side and client side PR. Do you have any more questions about this approach or is this clear now? I think the rubber will meet the road in the second part of this effort (i.e. the client side changes).

**Comment by chenba** [comment]
https://github.com/mozilla/fxa/pull/16214/files#diff-0352ea89ac02a9d40e96cb39d5a79447fce8763cdff17d27a4b966f1390b5702R167 generates a second kB on account creation.  Since the plan is to support both versions of key stretching simultaneously, how are we ensuring only one of those values are ever going to be used?

**Pull request closed without merging**
