### PR TITLE
fix(l10n): Fix profile-heading l10n label typo.

### PR DESCRIPTION
**Pull request by vbudhram**
Noticed this while working on other PRs.

### CODE REVIEW

**Review by dannycoates — APPROVED** [review]
should we also PR against fxa-content-server-l10n so we don't trigger a string change?

**Comment by clouserw** [comment]
Yes, that would be appreciated.  A global grep/sed should be quick and will be picked up correctly by pontoon.  /cc @peiying2

**Comment by vbudhram** [comment]
> A global grep/sed should be quick and will be picked up correctly by pontoon

Sounds good, I'll make that PR.

**Comment by vbudhram** [comment]
> Sounds good, I'll make that PR.

PR up in l10n repo https://github.com/mozilla/fxa-content-server-l10n/pull/484

**Pull request merged**
