### PR TITLE
chore(docs): remove unused VPN legal docs directories

### PR DESCRIPTION
**Pull request by advaith-unnikrishnan**
### Because
- Presence of old legal docs makes the uploading of new legal docs confusing

### This commit
- Removes the old legal docs from the `assets/legal` directory

### Issue that this pull request solves
Closes: #10816 

### Checklist

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests that pass locally.
- [x]  I have added the necessary documentation (if appropriate).
- [x]  I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

**Review by biancadanforth — CHANGES_REQUESTED** [review]
Thanks @advaith-unnikrishnan . The diff looks fine, but have you read our [contributing docs](https://github.com/mozilla/fxa/blob/main/CONTRIBUTING.md#sending-pull-requests)?

In particular, the patch must be GPG signed, and we have conventions for commit messages, bodies and PR descriptions for example. Can you update this PR accordingly? Here's an [example PR](https://github.com/mozilla/fxa/pull/10825).

An example commit message for this might be: "chore(docs): remove unused VPN legal docs directories".

**Comment by advaith-unnikrishnan** [comment]
@biancadanforth  Thanks for the update. I will update the PR based on the contribution guidelines.

**Comment by biancadanforth** [comment]
> @biancadanforth I have updated the pull request as per the contribution guidelines. Kindly review it.

I see that you updated the PR, but the commit has not been updated?

**Comment by advaith-unnikrishnan** [comment]
@biancadanforth  I have updated the commit. Kindly let me know if it's ok

**Comment by biancadanforth** [comment]
Hm... this still doesn't look right. It looks like you reverted the original diff with the last commit on this branch, so there are no changes in this PR anymore.

I recommend an interactive rebase if you are familiar with that where you drop the last commit and force push your local branch with the first two commits up.

Also your commits are still not [GPG signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits), though you checked that box in the[ PR description checklist](https://github.com/mozilla/fxa/pull/10867#issue-1040160907) above. When this is done successfully, it should look like this commit in the example PR I [referenced earlier](https://github.com/mozilla/fxa/pull/10867#pullrequestreview-794358554) with the "Verified" indicator:
Screen Shot 2021-11-05 at 10 54 38 AM

**Comment by biancadanforth** [comment]
@advaith-unnikrishnan , are you still working on this?

If there is no movement for two weeks (we are already at the 10 day mark), I will probably close or commandeer the PR.

**Comment by biancadanforth** [comment]
Well, due to two weeks of inactivity, I tried to commandeer this PR by:
* setting your fork as a remote,
* creating a branch that tracks this PR branch,
* making the change and pushing it to this PR branch

... But it didn't work -- likely because either:
1. This PR branch is your fork's `main` branch or
2. I don't have [permission](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) from you, the pull request author, to push commits to this branch.

Below is the output for posterity:

```
bdanforth ~/Projects/fxa (commandeer-pr10867) $ git remote -v
advaith	git@github.com:advaith-unnikrishnan/fxa.git (fetch)
advaith	git@github.com:advaith-unnikrishnan/fxa.git (push)
(suppressed)
bdanforth ~/Projects/fxa (main) $ git checkout -b commandeer-pr10867 advaith/main
Branch 'commandeer-pr10867' set up to track remote branch 'main' from 'advaith'.
Switched to a new branch 'commandeer-pr10867'
husky > post-checkout (node v16.12.0)

yarn.lock changed. You may want to run 'yarn install'.

To auto install next time set FXA_AUTO_INSTALL=1 or to 0 to disable this check.

bdanforth ~/Projects/fxa (commandeer-pr10867) $ git log --oneline -3
285941db2 (HEAD -> commandeer-pr10867, advaith/main) Revert "chore(docs):remove unused VPN Legal docs directories"
b09240fce Merge branch 'main' of https://github.com/advaith-unnikrishnan/fxa
c37ecc98c chore(docs):remove unused VPN Legal docs directories
bdanforth ~/Projects/fxa (commandeer-pr10867) $ git revert 285941db2
Removing assets/legal/mozilla_vpn_privacy_notice/en-US.pdf
Removing assets/legal/Mozilla_VPN_ToS/en-US.pdf
[commandeer-pr10867 a45986d39] Revert "Revert "chore(docs):remove unused VPN Legal docs directories""
 2 files changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 assets/legal/Mozilla_VPN_ToS/en-US.pdf
 delete mode 100644 assets/legal/mozilla_vpn_privacy_notice/en-US.pdf
bdanforth ~/Projects/fxa (commandeer-pr10867) $ git log --oneline -4
a45986d39 (HEAD -> commandeer-pr10867) Revert "Revert "chore(docs):remove unused VPN Legal docs directories""
285941db2 (advaith/main) Revert "chore(docs):remove unused VPN Legal docs directories"
b09240fce Merge branch 'main' of https://github.com/advaith-unnikrishnan/fxa
c37ecc98c chore(docs):remove unused VPN Legal docs directories
bdanforth ~/Projects/fxa (commandeer-pr10867) $ git push advaith main
husky > pre-push (node v16.12.0)
Audited within the last 24 hours, skipping
To github.com:advaith-unnikrishnan/fxa.git
 ! [rejected]            main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:advaith-unnikrishnan/fxa.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

As you can see from the output, the commit hashes here are identical to those in this PR except the newly added commit to make the desired change.

Anyway, I've spent enough time on this; I'm going to close this PR and unassign the issue for now.

**Pull request closed without merging**
