### PR TITLE
Embed bg color

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #3006

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@johngruen do you mean to have both commits in this PR or just the 2nd?

**Comment by johngruen** [comment]
ack...i mushed two things together here...will fix, i just meant to do the second

**Comment by johngruen** [comment]
Okay @shane-tomlinson cleaned up the PR

**Comment by shane-tomlinson** [comment]
@johngruen - there are a couple of failures on the payments server:
```
PASS src/App.test.tsx
  App/AppErrorBoundary
    ✓ renders children that do not cause exceptions (5ms)
    ✓ renders a general error dialog on exception in child component (54ms)
  App/AppErrorDialog
    ✓ renders a general error dialog (7ms)

  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [Error: bad]
        at reportException (/app/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at invokeEventListeners (/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/app/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/app/node_modules/react-dom/cjs/react-dom.development.js:397:16)
        at invokeGuardedCallback (/app/node_modules/react-dom/cjs/react-dom.development.js:454:31)
        at beginWork$$1 (/app/node_modules/react-dom/cjs/react-dom.development.js:23217:7)
        at performUnitOfWork (/app/node_modules/react-dom/cjs/react-dom.development.js:22211:12) Error: bad
        at BadComponent (/app/src/App.test.tsx:27:13)
        at renderWithHooks (/app/node_modules/react-dom/cjs/react-dom.development.js:15108:18)
        at mountIndeterminateComponent (/app/node_modules/react-dom/cjs/react-dom.development.js:17342:13)
        at beginWork$1 (/app/node_modules/react-dom/cjs/react-dom.development.js:18486:16)
        at HTMLUnknownElement.callCallback (/app/node_modules/react-dom/cjs/react-dom.development.js:347:14)
        at invokeEventListeners (/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/app/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/app/node_modules/react-dom/cjs/react-dom.development.js:397:16)
        at invokeGuardedCallback (/app/node_modules/react-dom/cjs/react-dom.development.js:454:31)
        at beginWork$$1 (/app/node_modules/react-dom/cjs/react-dom.development.js:23217:7)
        at performUnitOfWork (/app/node_modules/react-dom/cjs/react-dom.development.js:22211:12)
        at workLoopSync (/app/node_modules/react-dom/cjs/react-dom.development.js:22185:22)
        at renderRoot (/app/node_modules/react-dom/cjs/react-dom.development.js:21878:11)
        at scheduleUpdateOnFiber (/app/node_modules/react-dom/cjs/react-dom.development.js:21419:22)
        at scheduleRootUpdate (/app/node_modules/react-dom/cjs/react-dom.development.js:24319:3)
        at updateContainerAtExpirationTime (/app/node_modules/react-dom/cjs/react-dom.development.js:24347:10)
        at updateContainer (/app/node_modules/react-dom/cjs/react-dom.development.js:24436:10)
        at /app/node_modules/react-dom/cjs/react-dom.development.js:24963:7
        at unbatchedUpdates (/app/node_modules/react-dom/cjs/react-dom.development.js:21687:12)
        at legacyRenderSubtreeIntoContainer (/app/node_modules/react-dom/cjs/react-dom.development.js:24962:5)
        at Object.render (/app/node_modules/react-dom/cjs/react-dom.development.js:25042:12)
        at /app/node_modules/@testing-library/react/dist/pure.js:86:25
        at batchedUpdates$1 (/app/node_modules/react-dom/cjs/react-dom.development.js:21643:12)
        at act (/app/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:14)
        at act (/app/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1418:12)
        at render (/app/node_modules/@testing-library/react/dist/pure.js:82:26)
        at Object.<anonymous> (/app/src/App.test.tsx:29:31)
        at Object.asyncJestTest (/app/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
        at /app/node_modules/jest-jasmine2/build/queueRunner.js:43:12
        at new Promise (<anonymous>)
        at mapper (/app/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
        at /app/node_modules/jest-jasmine2/build/queueRunner.js:73:41

  console.error node_modules/react-dom/cjs/react-dom.development.js:19814
    The above error occurred in the <BadComponent> component:
        in BadComponent (at App.test.tsx:32)
        in AppErrorBoundary (at App.test.tsx:31)
    
    React will try to recreate this component tree from scratch using the error boundary you provided, AppErrorBoundary.

  console.error src/App.tsx:105
    AppError Error: bad
        at BadComponent (/app/src/App.test.tsx:27:13)
        at renderWithHooks (/app/node_modules/react-dom/cjs/react-dom.development.js:15108:18)
        at mountIndeterminateComponent (/app/node_modules/react-dom/cjs/react-dom.development.js:17342:13)
        at beginWork$1 (/app/node_modules/react-dom/cjs/react-dom.development.js:18486:16)
        at HTMLUnknownElement.callCallback (/app/node_modules/react-dom/cjs/react-dom.development.js:347:14)
        at invokeEventListeners (/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/app/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/app/node_modules/react-dom/cjs/react-dom.development.js:397:16)
        at invokeGuardedCallback (/app/node_modules/react-dom/cjs/react-dom.development.js:454:31)
        at beginWork$$1 (/app/node_modules/react-dom/cjs/react-dom.development.js:23217:7)
        at performUnitOfWork (/app/node_modules/react-dom/cjs/react-dom.development.js:22211:12)
        at workLoopSync (/app/node_modules/react-dom/cjs/react-dom.development.js:22185:22)
        at renderRoot (/app/node_modules/react-dom/cjs/react-dom.development.js:21878:11)
        at scheduleUpdateOnFiber (/app/node_modules/react-dom/cjs/react-dom.development.js:21419:22)
        at scheduleRootUpdate (/app/node_modules/react-dom/cjs/react-dom.development.js:24319:3)
        at updateContainerAtExpirationTime (/app/node_modules/react-dom/cjs/react-dom.development.js:24347:10)
        at updateContainer (/app/node_modules/react-dom/cjs/react-dom.development.js:24436:10)
        at /app/node_modules/react-dom/cjs/react-dom.development.js:24963:7
        at unbatchedUpdates (/app/node_modules/react-dom/cjs/react-dom.development.js:21687:12)
        at legacyRenderSubtreeIntoContainer (/app/node_modules/react-dom/cjs/react-dom.development.js:24962:5)
        at Object.render (/app/node_modules/react-dom/cjs/react-dom.development.js:25042:12)
        at /app/node_modules/@testing-library/react/dist/pure.js:86:25
        at batchedUpdates$1 (/app/node_modules/react-dom/cjs/react-dom.development.js:21643:12)
        at act (/app/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:14)
        at act (/app/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1418:12)
        at render (/app/node_modules/@testing-library/react/dist/pure.js:82:26)
        at Object.<anonymous> (/app/src/App.test.tsx:29:31)
        at Object.asyncJestTest (/app/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
        at /app/node_modules/jest-jasmine2/build/queueRunner.js:43:12
        at new Promise (<anonymous>)
        at mapper (/app/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
        at /app/node_modules/jest-jasmine2/build/queueRunner.js:73:41

PASS src/components/DialogMessage.test.tsx
```

**Comment by lmorchard** [comment]
FWIW, this stuff isn't a real error - it's a test of an error handler. I've got some tweaks to make that output quiet down in another PR.

```
  App/AppErrorDialog
    ✓ renders a general error dialog (7ms)

  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [Error: bad]
```

**Comment by lmorchard** [comment]
This is the real cause of the failure - an npm module security advisory down at the bottom of the output:
```
Unfiltered advisories:
  https://npmjs.com/advisories/1184
```

**Comment by lmorchard** [comment]
Actually, [looks like my PR's been merged](https://github.com/mozilla/fxa/commit/7c9565410a56cb5ce74c93b7a27e711fc56058e8), so maybe a re-run of the tests here will work?

**Comment by johngruen** [comment]
yeah i can rebase

**Pull request merged**
