### PR TITLE
task(all): Remove ':' characters from npm targets

### PR DESCRIPTION
**Pull request by dschom**
## Because

- A ':' character indicates that a script is globally available

## This pull request

- Converts : to -

## Issue that this pull request solves

Closes: # (issue number)

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Other information (Optional)

Documentation of ':' character in script names can be found here: https://yarnpkg.com/getting-started/qa#how-to-share-scripts-between-workspaces 

The following scripts were located, and colons were replaced with hyphens. 
```
build:client
build:server
build-storybook:copy-locales
build-storybook-copy-templates
lint:eslint
lint:style
merge-ftl:test
start:prod
test:cov
test:default
test:e2e
test:frontend
test:integration
test:integration-disabled
test:jest
test:jest:unit
test:jest:integration
test:mocha
test:mocha:unit
test:mocha:integration
test:server
test:unit
test:watch

### CODE REVIEW

**Comment by pdehaan** [comment]
And here's an inverted one that looks for `:` in the command part of the script. Not all will be valid since I'm far too lazy to bother with lookahead/lookbehind to detect port numbers or `https?://` protocols. But I'll do my best to manually remove the obviously invalid ones below for your reading pleasure and manually add a "WHY" context column:

<details>
<summary>clicko expando 🪄 </summary>

```js
import fg from "fast-glob";

const packages = await fg("packages/*/package.json");

for (const pkg of packages) {
  let hasHeader = false;
  const { default: pkgJson } = await import(`./${pkg}`, {
    assert: { type: "json" },
  });
  for (const [name, cmd] of Object.entries(pkgJson.scripts || {})) {
    if (cmd.includes(":")) {
      if (!hasHeader) {
        console.log(`\n### ${pkgJson.name}`);
        console.log("SCRIPT | COMMAND\n----|----")
        hasHeader = true;
      }
      console.log(`\`${name}\` | \`${cmd}\``);
    }
  }
}
```
</details>


### fxa-auth-server
SCRIPT | COMMAND | WHY
----|----|---
`l10n-prime` | `yarn l10n:prime fxa-auth-server` | `l10n:prime`

### fxa-content-server
SCRIPT | COMMAND | WHY
----|----|----
`l10n-prime` | `yarn l10n:prime fxa-content-server` | `l10n:prime`
`start` | `node scripts/check-local-config && yarn l10n-prime && NODE_OPTIONS=--openssl-legacy-provider grunt l10n-create-json l10n-generate-tos-pp:app && pm2 start pm2.config.js && ../../_scripts/check-url.sh localhost:3030/bundle/app.bundle.js && npm run build-css` | `l10n-generate-tos-pp:app`
`start-production` | `NODE_ENV=production NODE_OPTIONS=--openssl-legacy-provider grunt build && npm run build-css && CONFIG_FILES=server/config/local.json,server/config/production.json grunt serverproc:dist` | `serverproc:dist`

### fxa-payments-server
SCRIPT | COMMAND | WHY
----|----|----
`postinstall` | `yarn l10n:prime fxa-payments-server` | `l10n:prime`
`l10n-prime` | `yarn l10n:prime fxa-payments-server` | `l10n:prime`
`l10n-bundle` | `yarn l10n:bundle fxa-payments-server react,payments`  | `l10n:bundle`

### fxa-react
SCRIPT | COMMAND | WHY
----|----|----
`l10n-prime` | `yarn l10n:prime fxa-react` | `l10n:prime`

### fxa-settings
SCRIPT | COMMAND | WHY
----|----|----
`l10n-prime` | `yarn l10n:prime fxa-settings` | `l10n:prime`
`l10n-bundle` | `yarn l10n:bundle fxa-settings branding,react,settings` | `l10n:bundle`
`legal-clone` | `yarn legal:clone fxa-settings` | `l10n:clone`

### fxa-shared
SCRIPT | COMMAND | WHY
----|----|----
`test` | `yarn test:mocha && yarn test-jest` | `test:mocha`

**Comment by dschom** [comment]
@pdehaan Thanks for the detailed searching. Definitely found some stuff that my regex somehow missed. I've just pushed updates. Mind doing one more pass?

**Comment by pdehaan** [comment]
Latest script results (but I wrote the script, so let that factor in to your confidence ratings) showed these results.
Note that all of them seem to be Grunt task names, ie: `grunt merge-ftl:test`, `grunt l10n-generate-tos-pp:app`, `grunt merge-ftl:test`. 

<details>
<summary>beautiful markdown tables</summary>

### fxa-auth-server
SCRIPT | COMMAND
----|----
`merge-ftl-test` | `yarn l10n-prime && grunt merge-ftl:test`

### fxa-content-server
SCRIPT | COMMAND
----|----
`start` | `node scripts/check-local-config && yarn l10n-prime && NODE_OPTIONS=--openssl-legacy-provider grunt l10n-create-json l10n-generate-tos-pp:app && pm2 start pm2.config.js && ../../_scripts/check-url.sh localhost:3030/bundle/app.bundle.js && npm run build-css`
`start-production` | `NODE_ENV=production NODE_OPTIONS=--openssl-legacy-provider grunt build && npm run build-css && CONFIG_FILES=server/config/local.json,server/config/production.json grunt serverproc:dist`

### fxa-payments-server
SCRIPT | COMMAND
----|----
`merge-ftl-test` | `yarn l10n-prime && grunt merge-ftl:test`

### fxa-react
SCRIPT | COMMAND
----|----
`merge-ftl-test` | `yarn l10n-prime && grunt merge-ftl:test`

### fxa-settings
SCRIPT | COMMAND
----|----
`merge-ftl-test` | `yarn l10n-prime && grunt merge-ftl:test`
</details>

**Comment by dschom** [comment]
Cool, so I think it's fine for those grunt scripts to contain colons.

**Comment by pdehaan** [comment]
Apologies, my greps are getting worse and worse, but these may or may not be something:

```sh
git grep -En "\b\w+:\s?\w+\b" ':!.yarn' ':!yarn.lock' ':!**/CHANGELOG.md' | grep yarn

packages/fxa-payments-server/package.json:23:    "test-frontend:watch": "yarn merge-ftl-test && SKIP_PREFLIGHT_CHECK=true PUBLIC_URL=/ INLINE_RUNTIME_CHUNK=false rescripts test",
packages/fxa-settings/README.md:517:This package uses [Jest](https://jestjs.io/) to test its code. By default `yarn test` will test all JS files under `src/`. Running `yarn test:coverage` will also provide a coverage report, which should be respected.
packages/fxa-settings/package.json:25:    "test:coverage": "yarn legal-clone && yarn test --coverage --watchAll=false",
```

**Pull request merged**
