### PR TITLE
chore(deps): update shrinkwrap in the fxa-content-server

### PR DESCRIPTION
**Pull request by vladikoff**
Testing a shrinkwrap update, I suspect there could be breaking changes in the test dependencies

### CODE REVIEW

**Comment by vladikoff** [comment]
Ref: https://github.com/theintern/digdug/issues/75

**Comment by vladikoff** [comment]
waiting on https://github.com/theintern/digdug/issues/75#issuecomment-501509209

**Comment by shane-tomlinson** [comment]
@vladikoff - according to [this comment](https://github.com/theintern/digdug/issues/75#issuecomment-501525252), 2.2.12 is out now. Mind updating?

**Comment by shane-tomlinson** [comment]
@vladikoff is this still needed?

**Comment by vladikoff** [comment]
yeah, updated the PR

**Comment by vladikoff** [comment]
@shane-tomlinson this should be good now :)

**Pull request merged**
