### PR TITLE
Add npm run scripts to simplify attaching the node debugger

### PR DESCRIPTION
**Pull request by 6a68**
I'm not sure I'm doing this right, or if this would be useful for anybody else, but this is the recipe I've gotten working for attaching to a server process locally:

1. Start all the things from top-level in the monorepo with `npm install && npm start`
2. Choose a server to debug, and `./pm2 stop $server_id` to stop the managed process
3. Rummage around inside per-package npm run scripts to locate the actual server script (not a script that forks another script)
4. Run that script from the command-line with `node --inspect` instead of `node`
5. Connect to the process from the chrome debugger

This PR makes it possible to replace steps 3 and 4 with `npm run start-dev-debug`, at least for the content and payments servers:

1. Start all the things from top-level in the monorepo with `npm install && npm start`
2. Choose a server to debug, and `./pm2 stop $server_id` to stop the managed process
3. Go to the content or payments server directory, then `npm run start-dev-debug`
4. Connect to the process from the chrome debugger

Good? Helpful? Meh? Feedback welcome.

### CODE REVIEW

**Comment by chenba** [comment]
Would be nice if they are mentioned in a README somewhere.

Also, squash commits?

**Comment by 6a68** [comment]
@chenba added docs, what do you think? (docs may also be relevant to @lmorchard's interests)

**Comment by lmorchard** [comment]
> docs may also be relevant to @lmorchard's interests

Not sure? I've never actually used the node debugger for anything serious. Does this do anything in CircleCI? (That's mainly where I'm working on docs at the moment)

**Comment by 6a68** [comment]
> > docs may also be relevant to @lmorchard's interests
> 
> Not sure? I've never actually used the node debugger for anything serious. Does this do anything in CircleCI? (That's mainly where I'm working on docs at the moment)

Nope, doesn't affect CircleCI at all, but I did add a test debugging section to the main README.

**Comment by chenba** [comment]
👍 Thanks for adding the docs!

**Pull request merged**
