### PR TITLE
fix(settings): only set hover css when supported

### LINKED ISSUE #6371: [FxA-Settings] “Make primary” button is displayed in hovered state after tapping on it on iOS
**Build**
Stage [Train 1.186.0]

**Affected platforms**
iOS 13.6 

**Affected devices**
iPhone 11

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/
2. Login using an user that has already added a secondary email
3. Tap on “Make primary” button.

**Expected results**
The “Make primary” button returns to the enabled state.

**Actual Results**
The “Make primary” button is displayed in the hover state.

issue5

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2512)
┆Issue Number: FXA-2512

### PR DESCRIPTION
**Pull request by dannycoates**
## Because

- iOS is weird about `hover` effects

## This pull request

- uses a `@media` query to set the hover styles

## Issue that this pull request solves

fixes #6371

### CODE REVIEW

**Comment by jodyheavener** [comment]
Interesting. Doesn't the hover effect go away when you tap outside of the button?

**Review by chenba — APPROVED** [review]
TIL

**Comment by dannycoates** [comment]
> Maybe we should wontfix

No, setting hover effects when hover isn't supported creates unexpected and inconsistent results across browsers.

**Comment by jodyheavener** [comment]
Shouldn't we do it for all links then?

**Comment by dannycoates** [comment]
> Shouldn't we do it for all links then?

What links? where else do we define `:hover` styles?

**Comment by jodyheavener** [comment]
I don't think we write any other custom hover styles, but we do have a handful of hover styles coming from Tailwind classes, e.g. [here](https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/components/PageAvatar/Capture.tsx#L49:L51) and [here](https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/components/AlertBar/index.tsx#L61:L61).

**Pull request merged**
