### PR TITLE
fix(fxa-settings):change close button to cancel in delete

### PR DESCRIPTION
**Pull request by Jane-Kotovich**
## Because

- Dashboard in delete account on first step instead of button Cancel we had Close
 
106765284-4fa43100-6641-11eb-8340-3c96835c5aa7

## This pull request

- Change button Close to button Cancel

## Issue that this pull request solves

Closes: #7414

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

https://user-images.githubusercontent.com/76935202/113871064-dc13d100-97f5-11eb-86e9-53ecee326b6b.mov

## Other information (Optional)

macOS Catalina
Google Chrome

### CODE REVIEW

**Comment by Jane-Kotovich** [comment]
@jodyheavener I ended up making new pull request with changes pr so it fits task

**Comment by jodyheavener** [comment]
@Jane-Kotovich Looks good we just need to squash those two commits together 😀

**Comment by Jane-Kotovich** [comment]
@jodyheavener I spent couple of hr trying to rebase it but it just won't work. Im running:
git rebase -i HEAD~2 and then I change second to fixup and then it won't let me do anything - I can't quite I can't run rebase --continue and if I save and close it still hangs on there as not finished one 🤯

**Comment by jodyheavener** [comment]
@Jane-Kotovich You should be able to interactive rebase and squash (instead of fixup) the second commit

- `git rebase -i HEAD~2`
- `squash 44018a64c Ffix tests`
- Set the correct commit message
- `git push force --with-lease`

**Comment by Jane-Kotovich** [comment]
@jodyheavener oh no, now some test failed.. how is it come if I have change only two files and before they were passing the test ..

**Pull request closed without merging**
