### PR TITLE
fix(admin-server): move ts-morph to dependencies

### PR DESCRIPTION
**Pull request by jodyheavener**
Should fix broken admin server

### CODE REVIEW

**Review by LZoog — APPROVED** [review]
TY!

**Comment by dannycoates** [comment]
the playwright tests are failing because content-server is responding with `Error occured while trying to proxy: localhost:3030/settings`

I added the pm2 logs to the CI artifacts to see if that helps debug

**Comment by dannycoates** [comment]
hmmm
```
2021-12-03T22:47:13: The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
```

**Comment by dannycoates** [comment]
so settings-react is the memory hog of our pm2 processes. on my machine over 1G total for the rescripts and child processes, so it makes sense it's the first to be killed. idk why we're hitting this _now_, but it seems like circleci is being stingier with resources recently. anyway, it isn't until the browser process opens that settings is killed, so we can't just reduce concurrency of startup, which i did anyway while debugging, and it's prob good to keep those changes, so i folded and bumped the instance size to a large for now. unsatisfying but unblocks us

**Pull request merged**
