### PR TITLE
fix(emails): Add date and time in verifyShortCodeEmail template

### PR DESCRIPTION
**Pull request by Yogita98**
## Because

- Date and time could be an important field to display so as to emphasize the activation limited time to the user

## This pull request

- Aims to display the date and time component in the email template

## Issue that this pull request solves

Closes: #8341 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)
image

## Other information (Optional)

Any other information that is important to this pull request.

### CODE REVIEW

**Comment by Yogita98** [comment]
Hey @mozilla/fxa-devs
Can anyone review my PR? I have also modified the tests accordingly. One thing that I'd like to highlight is that the timeout set for the tests [here](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/scripts/test-local.sh#L13) is just 5s and maybe because of which timeout errors are being thrown, I had to make it 30s for the tests to pass locally.

**Review by LZoog — APPROVED** [review]
Before:
image


After:
image

LGTM, thanks @Yogita98! 😃

**Comment by LZoog** [comment]
> One thing that I'd like to highlight is that the timeout set for the tests here is just 5s and maybe because of which timeout errors are being thrown, I had to make it 30s for the tests to pass locally.

Huh, that's strange. It seems to be passing fine in Circle CI so we'll leave it but that's good to know. 🤔

**Comment by Yogita98** [comment]
Okay no worries! And thanks for reviewing my PR @LZoog

**Pull request merged**
