### PR TITLE
fix(fxa-settings): dynamic loading svg fix

### PR DESCRIPTION
**Pull request by meandavejustice**
Turned out to be some weirdness with create-react-app
found the solution here: https://github.com/facebook/create-react-app/issues/5276#issuecomment-665628393

Closes: #6975

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

**Comment by meandavejustice** [comment]
This is now failing on all of the Connected Services tests, it appears that we import things differently within the tests 🤔

**Comment by meandavejustice** [comment]
cc/ @chenba we'll probably want to do a point release with this, let's see if there's anything else we want to get in tomorrow though

**Comment by chenba** [comment]
When I tried this locally I got:

`Unhandled Rejection (Error): Cannot find module '!!@svgr/webpack?-svgo,+titleProp,+ref!./web.svg'`

`yarn build` was successful though.

**Comment by meandavejustice** [comment]
@chenba So apparently my workaround for the tests its what is causing the failure.

It works correctly when hard coded:
```
ImportedIconRef.current = (
          await import(`!!@svgr/webpack?-svgo,+titleProp,+ref!./${name}.svg`)
        ).default;
```

But fails with the `prefix` variable. Which I was using to detect when a test is being run. 🤔 

We may just statically load these icons if we can't find a reasonable workaround for the test failures, cus the dynamic loading isn't really giving us that many benefits anyways...

**Comment by jodyheavener** [comment]
🚗 I'm all for manually loading each SVG 🚗

**Comment by chenba** [comment]
image
image

Old vs. new.  Does that look right?

**Review by chenba — APPROVED** [review]

**Pull request merged**
