### PR TITLE
feat(caa): Add connect another service experiment

### PR DESCRIPTION
**Pull request by vbudhram**
Migrated this from https://github.com/mozilla/fxa-content-server/pull/6764/files, so it doesn't rot.

### CODE REVIEW

**Comment by vbudhram** [comment]
@davismtl @vbudhram @juliemccracken to sync up and get prioritize this.

**Comment by vbudhram** [comment]
I'm closing this for now, can reopen if/when prioritized.

**Comment by philbooth** [comment]
> I'm closing this for now, can reopen if/when prioritized.

I got pretty excited for a second when I saw this subject line resurface in my bugmail. 😞

**Comment by davismtl** [comment]
It'll likely appear in a different form. For example, if we know that users have multiple devices, we might link them to the accounts product page on Mozilla.org to learn about our other great services.

**Pull request closed without merging**
