### PR TITLE
docs(adrs): draft auth-db-mysql adr

### PR DESCRIPTION
**Pull request by dannycoates**

### CODE REVIEW

**Comment by 6a68** [comment]
This looks good so far. I guess the alternatives to consider would be doing nothing, and moving auth-db back to its own physical layer, to regain the defense-in-depth advantages of a separate database microservice.

**Comment by chenba** [comment]
Sounds good to me.

> This separation was deemed unimportant at some point, though the details are probably lost to history ...

This feels like the kind of thing rfk would remember.

**Comment by dannycoates** [comment]
> This feels like the kind of thing rfk would remember.

Technically, ***I*** should remember since it happened during my first tour 😜

**Comment by enote-kane** [comment]
Just out of curiosity: how is the fxa-email-service going to deal with the removal?

**Comment by dannycoates** [comment]
> how is the fxa-email-service going to deal with the removal?

good question. We'll update fxa-email-service to connect to the db directly.

**Pull request merged**
