### PR TITLE
perf(content): Optimize tailwind output

### PR DESCRIPTION
**Pull request by vpomerleau**
## Because

* Transferred tailwind.out.css was very large (>3mb) and unused styles were not purged

## This pull request

* Optimize build-css for production

## Issue that this pull request solves

Closes: #FXA-9129

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Other information (Optional)

After the initial change, the tailwind file is down from >5 mb to just over 0.1mb.
A second commit adds a minification step, this reduces a tad further to 0.06mb.

### CODE REVIEW

**Review by chenba — APPROVED** [review]
😍 🏅 🏆

**Comment by pdehaan** [comment]
🤯 
```diff
- 5.1M  app/styles/tailwind.out.css (Done in 6_774ms.)
+  67K  app/styles/tailwind.out.css (Done in 435ms.)
```

```sh
[main] $ npm run build-css

> fxa-content-server@0.0.0 build-css
> tailwindcss --postcss -i ./app/styles/tailwind.css -o ./app/styles/tailwind.out.css

Rebuilding...

Done in 6_774ms.

[main] $ ls -lash app/styles/tailwind.out.css
10472 -rw-r--r--  1 pdehaan  staff   5.1M  6 Feb 23:30 app/styles/tailwind.out.css
```

```sh
$ gh pr checkout 16357

[FXA-9129] $ npm run build-css

> fxa-content-server@0.0.0 build-css
> NODE_ENV=production tailwindcss --postcss -i ./app/styles/tailwind.css -o ./app/styles/tailwind.out.css --minify

Rebuilding...

Done in 435ms.

[FXA-9129] $ ls -lash app/styles/tailwind.out.css
136 -rw-r--r--  1 pdehaan  staff    67K  6 Feb 23:31 app/styles/tailwind.out.css
```

**Review by vbudhram — APPROVED** [review]
Awesome 💪🏽 🥇

**Comment by clouserw** [comment]
wow, nice job @vpomerleau

**Comment by pdehaan** [comment]
Actually, before we get too far off this thread, can i get some sanity checks on this greppin':
```sh
git grep -Pin "tailwindcss\s" -- "**/package.json" | cat

packages/fxa-admin-panel/package.json:9:    "build-css": "npx tailwindcss -i ./src/styles/tailwind.css -o ./src/styles/tailwind.out.css --postcss",
packages/fxa-content-server/package.json:8:    "build-css": "NODE_ENV=production tailwindcss --postcss -i ./app/styles/tailwind.css -o ./app/styles/tailwind.out.css --minify",
packages/fxa-payments-server/package.json:8:    "build-css": "npx tailwindcss --postcss -i ./src/styles/tailwind.css -o ./src/styles/tailwind.out.css",
packages/fxa-react/package.json:17:    "build-css": "npx tailwindcss -i ./styles/tailwind.css -o ./styles/tailwind.out.css",
packages/fxa-settings/package.json:10:    "build-css": "NODE_ENV=production tailwindcss -i ./src/styles/tailwind.css -o ./src/styles/tailwind.out.css --postcss",
```

| package | production? | minified?
|:----|:----:|:----:|
`fxa-admin-panel` | 🚫  | 🚫 
`fxa-content-server` | ✔️ | ✔️ 
`fxa-payments-server` | 🚫  | 🚫
`fxa-react` | 🚫  | 🚫
`fxa-settings` | ✔️   | 🚫

**Comment by chenba** [comment]
The minification could be happening further down the build chain.  E.g. content server has a 'cssmin' grunt task.

**Comment by pdehaan** [comment]
Possibly drop another 27KB from the fxa-settings' src/styles/tailwind.out.css file by adding `--minify` (it's seemingly already a `NODE_ENV=production` build):
```sh
[main] $ cd fxa-settings
[main] $ yarn build-css
Rebuilding... Done in 530ms.
[main] $ ls -lash src/styles/tailwind.out.css # 83K

# set `--minify`
[main] $ yarn build-css
Rebuilding... Done in 665ms.
[main] $ ls -lash src/styles/tailwind.out.css # 56K
```

**Comment by pdehaan** [comment]
As for fxa-admin-panel, it gets a bit more interestin'&hellip; 4.9MB down to 16K (but also, drops the build time from 6s to 234ms):

```sh
[main] $ yarn build-css
Rebuilding... Done in 6_088ms.
[main] $ ls -lash src/styles/tailwind.out.css # 4.9M

# Set `NODE_ENV=production`
[main] $ yarn build-css
# Rebuilding... Done in 189ms.
[main] $ ls -lash src/styles/tailwind.out.css # 25K

# set `--minify`
[main] $ yarn build-css
# Rebuilding... Done in 234ms.
[main] ls -lash src/styles/tailwind.out.css # 16K
```

**Comment by pdehaan** [comment]
fxa-react is least interesting, going from 14K down to 6.2K with `NODE_ENV=production` and `--minify`. Not sure why there isn't as big a difference there, but :shrug:

**Comment by chenba** [comment]
> Possibly drop another 27KB from the [fxa-settings](https://mozilla-hub.atlassian.net/browse/FXA-settings)' src/styles/tailwind.out.css file by adding `--minify` (it's seemingly already a `NODE_ENV=production` build):
> 
> ```shell
> [main] $ cd fxa-settings
> [main] $ yarn build-css
> Rebuilding... Done in 530ms.
> [main] $ ls -lash src/styles/tailwind.out.css # 83K
> 
> # set `--minify`
> [main] $ yarn build-css
> Rebuilding... Done in 665ms.
> [main] $ ls -lash src/styles/tailwind.out.css # 56K
> ```

After webpack the difference is actually 96 bytes.

**Comment by pdehaan** [comment]
Ah yes, your previous comments re: 
> "The minification could be happening further down the build chain. E.g. content server has a 'cssmin' grunt task."

Probably easiest to wait for this and @xlisachan's PRs to find their way to production and then I can rerun the Lighthouse audits and see if I can find a way to automate scraping auth'ed pages w/ Lighthouse (via Playwright?) and/or WebPageTest (via their bespoke scripting langauge).

**Pull request merged**
