### PR TITLE
chore(test): Use Firefox 65 for Circle tests

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Why 65? Dunno, just to see if it can be done. 58 is a while ago.

### CODE REVIEW

**Comment by vladikoff** [comment]
@shane-tomlinson warning, the tests didn't run ?

> @circleci-checks
test Successful in 4m — Workflow: test

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson warning, the tests didn't run ?

No tests means no failures! Great. Fantastic. Perfect. Brilliant even!

**Comment by vladikoff** [comment]
I kicked off a similar run for this https://github.com/mozilla/fxa/pull/1343 to test out https://github.com/theintern/digdug/issues/75

**Comment by shane-tomlinson** [comment]
Closing until I can figure out the failing avatar test.

**Pull request closed without merging**
