### PR TITLE
chore(csp): Change CSP logging format to mozlog 2.0

### PR DESCRIPTION
**Pull request by jbuck**
This still needs some test changes before merging, but one step closer to getting off heka!

### CODE REVIEW

**Comment by jbuck** [comment]
I am not going to lie, I am incredibly surprised that this passed tests. Should, uh, we merge it?

**Comment by shane-tomlinson** [comment]
> I am not going to lie, I am incredibly surprised that this passed tests. Should, uh, we merge it?

Can you verify there is a test for this?

**Comment by jbuck** [comment]
https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/tests/server/routes/post-csp.js

**Comment by shane-tomlinson** [comment]
Huh, they *are* failing locally:

Screenshot 2019-06-10 at 17 25 46

That seems to imply server tests are *not* run on Circle. Opening an issue.

**Pull request merged**
