### PR TITLE
feat(trailhead): Hook up new newsletters to backend.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
issue #1102

@vbudhram - r?

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Shoot, newsletters aren't being saved to the resume token.. Putting WIP on this.

**Comment by shane-tomlinson** [comment]
AAAGH, I totally forgot.. We send the resume token in the email on the step before CWTS.... !@$!@#%#@!!@#$!@$@!

@ryanfeeley, @davismtl - we can't put the newsletters on CWTS if we want all of:

1. The email to be sent from the screen where the user enters their passwords.
1b. (related) The email to be sent even if the user never submits CWTS.
2. The user to be opted in even if they verify on a 2nd device and close the tab here.

**Comment by vbudhram** [comment]
> We send the email in the page where the user enters their password.

Ugh, didn't realize that. A couple thoughts

* Could we add a new auth-server endpoint to emit newsletters notifications. This would get triggered when the user click continue on CWTS page.
* Was there a significant drop in registration rates if we delayed the email until after CWTS? Do the email reminders help minimize the problem?

**Comment by davismtl** [comment]
> Was there a significant drop in registration rates if we delayed the email until after CWTS? Do the email reminders help minimize the problem?

I'm not sure about this since we're not tracking CWTS properly. Maybe @irrationalagent has other metrics.
https://github.com/mozilla/fxa/issues/938

My high level estimate is that 50% of users will drop:
https://analytics.amplitude.com/mozilla-corp/chart/new/z59cbf8 

Ideally, if they drop at this stage, we want to make sure that they're still registered. Depending on email reminder doesn't inspire confidence.

> The email to be sent from the screen where the user enters their passwords.
1b. (related) The email to be sent even if the user never submits the choose what to sync screen.

This one seems resolvable. Although, clearly I don't know the scope.

> The user to be opted in even if they verify on a 2nd device and close the tab here.

This feels like a UX problem we need to figure out. I'll sync up with @ryanfeeley .

**Comment by davismtl** [comment]
@shane-tomlinson @vbudhram could we trigger the sending of the email confirmation after the initial form submit but _just_ delay sending for like 15-20 seconds to make sure they don't get distracted with an email notification and that they select their newsletters.

**Comment by irrationalagent** [comment]
By my count about 87% of flows that get to the account creation stage (valid email/pw) see the choose what to sync screen https://sql.telemetry.mozilla.org/queries/62869/source

we don't seem to have any metrics on CWTS engagement though

**Comment by shane-tomlinson** [comment]
The overall easiest thing to do is to move the email checkboxes back to the enter password screen.

Other possible options - 

* @vbudhram suggests adding a new endpoint on the auth server that allows someone with a sessionToken to notify basket of the intent to opt-in to a newsletter. This would require changes on basket, right now a user can only be opted in to newsletters once they become verified. I think this solution could work, I'm worried about the complexity this late in the cycle and the cross-team dependencies.
* @davismtl mentioned signing up the user on the "enter password page" but not sending the email for 20 seconds or so. If the user opts-in to marketing on CWTS, then we would send an updated ResumeToken to the backend to be sent out in the email. This approach would require keeping a queue of emails to be sent similar to verification reminders, and we'd have to be able to update entries in the queue. I'm really hesitant to add this kind of complexity this late in the cycle too.
* Do not sign the user up on the "enter password page", but do so on CWTS. Auto-submit CWTS after N seconds. I'm not sure what this means for the front-end code, but could work? @davismtl thinks there might be a huge drop-off in registrations though, plus auto-submit feels a bit gross.
* Send a 2nd email with an updated ResumeToken if the user opts in to any newsletters on CWTS. This just seems like we'll be spamming users, and I imagine cause a lot of confusion.

What else? cc @ryanfeeley, @davismtl, @vbudhram and @rfk because well, he often has insights on this sort of problem.

**Comment by vbudhram** [comment]
> I'm worried about the complexity this late in the cycle and the cross-team dependencies.

That is a fair concern, I am not 100% sold on this so late in the game either.

Of the possible solutions listed above, I think having check boxes on the signup page is the most straightforward engineering option.

**Comment by shane-tomlinson** [comment]
Expanding on @vbudhram's idea of adding a new endpoint on the auth server that allows someone with a sessionToken to notify basket of the intent to opt-in to a newsletter.

I can imagine this working kind of like so:

* We still send the signup verification email from the "enter your password page"
* On the CWTS screen, if the user opts-in to a newsletter, we call a new auth-server endpoint with the list of newsletters.
* If the user has verified their email, notify basket immediately. 
  * Maybe we could do this by calling Basket's [/subscribe.json](https://github.com/mozmeao/basket/blob/8ffa8f16145136788e7de7c1feb7a304756b6050/basket/urls.py#L21) using the [API_KEY the basket proxy uses](https://github.com/mozilla/fxa/blob/88ec33bcf199ab82d99dfa88e7995ba567bd0fc5/packages/fxa-basket-proxy/lib/basket/index.js#L41) (or provision a new API key).
* If the user has *not yet* verified their email, place the list of subscriptions into redis, keyed by userid.
  * When the user verifies their email, check if there are any subscriptions in redis. If so send the list along with the [verified message](https://github.com/mozilla/fxa/blob/88ec33bcf199ab82d99dfa88e7995ba567bd0fc5/packages/fxa-auth-server/lib/routes/account.js#L195)

This would give us all the properties we want.
* Email sent on password page
* Newsletter Opt-in on CWTS and doesn't explode the "enter password" page.
* Doesn't matter if user opts-in after verifying
* Doesn't matter if user never submits CWTS
* Doesn't involve multiple emails to update the ResumeToken
* Doesn't involve delaying emails to wait for CWTS input

@philbooth - Does shoving this type of info into Redis seem reasonable/viable? Would it be a challenge?

I'm sure I haven't thought through a load of corner cases, but this seems like it could work. I'm not convinced we'd be done in 2 days with existing workload & schedules, but could be convinced otherwise by someone who knows Redis & the backend better than I do.

**Comment by philbooth** [comment]
> Does shoving this type of info into Redis seem reasonable/viable? Would it be a challenge?

Yep, seems reasonable. No challenges I can see, the Redis abstraction we have in `fxa-shared` is pretty straightforward to use I think, just make sure you specify your own key prefix and suitable values for min/max connections based on expected usage.

One thing I recommend doing ahead of time is a quick back-of-a-fag-packet calculation of the expected data size, just so you can give messrs Morrison and Buckley a heads up of the likely effects in prod. Doesn't have to be too precise, just multiply the upper bound of your expected record count by the key length (including prefix) plus the size of your serialised data, then round it up a bit.

**Comment by shane-tomlinson** [comment]
I'm calling this ready for review.

You can check that opting in to emails is propagated on signup verification using this patch:

```diff
diff --git a/packages/fxa-content-server/app/scripts/models/account.js b/packages/fxa-content-server/app/scripts/models/account.js
index a851e2c46..25b952765 100644
--- a/packages/fxa-content-server/app/scripts/models/account.js
+++ b/packages/fxa-content-server/app/scripts/models/account.js
@@ -642,6 +642,8 @@ const Account = Backbone.Model.extend({
       options.newsletters = newsletters;
     }
 
+    console.log('newsletters', newsletters);
+
     return this._fxaClient.verifyCode(this.get('uid'), code, options)
       .then(() => {
         if (marketingOptIn) {
```

### Email-first based signup desktop

Screenshot 2019-05-23 at 18 30 17

### Email-first based signup mobile

Screenshot 2019-05-23 at 18 30 36

### Legacy signup desktop

Screenshot 2019-05-23 at 18 40 24


### Legacy signup mobile

Screenshot 2019-05-23 at 18 40 33

### CWTS desktop

Screenshot 2019-05-23 at 18 30 54


### CWTS mobile

Screenshot 2019-05-23 at 18 31 03

@mozilla/fxa-devs - r?

**Comment by davismtl** [comment]
Just to make sure that this was seen:
https://github.com/mozilla/fxa/issues/1241

**Pull request merged**
