### PR TITLE
feat(docs): add new component map

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by vladikoff** [comment]
@rfk @shane-tomlinson @ckarlof @jrgm updated the component map

Raw Link: https://raw.githubusercontent.com/mozilla/fxa/map2/docs/img/fxa.png


Anything missing? Feedback? (Also: the lucid chart link should allow anyone to edit)

**Comment by ckarlof** [comment]
e8nzc

**Comment by vladikoff** [comment]
https://www.lucidchart.com/documents/edit/677146e7-0fb8-4486-99a7-7eacaa16b6be/0

**Comment by jrgm** [comment]
One note: auth-server does not run a verifier, but fxa-oauth does. (I suppose you could note that oauth also uses a squid server, but that is probably too much detail).

**Comment by rfk** [comment]
@vladikoff I finally got my paid lucidchart account set up, but it doesn't look like I can edit the linked document, does it need to be shared with me explicitly?  (rkelly@mozilla.com is my newly-empowered lucidchart user account)

**Comment by vladikoff** [comment]
@rfk please try again, i just readded the Org and your account manually

**Comment by michielbdejong** [comment]
IMHO the clients connect both to the syncserver and the tokenserver, and the tokenserver needs access to the browserid verifier. See also https://github.com/michielbdejong/fxa-self-hosting#architecture for the diagram of how I linked my Docker containers together for self-hosting.

**Comment by vladikoff** [comment]
It looks like if we  link the lucid chart document it will be cached in github views but should be "auto" updated for those that view http://fxa.readthedocs.org/en/latest/#people-and-places

**Comment by rfk** [comment]
@vladikoff I updated the map a little:

* oauth and tokenserver both run their own local instance of browserid-verifer
* IIUC, auth-mailer is conceptually the thing that talks to SES, even though they're both on the same box currently
* added reference to server-syncstorage for the sync component
* adjusted the flow of data between auth, oauth and profile servers (which is frankly a bit of a mess at the moment, so it doesn't do the diagram any favours...)

How does it look?

**Comment by rfk** [comment]
Also I wasn't really sure how you wanted me to go about linking to and/or exporting it...?

**Comment by vladikoff** [comment]
@rfk Awesome! going to update this and add it!

**Pull request merged**
