### PR TITLE
storybook(fxa-settings): Recreate ConfirmResetPassword from backbone in react

### PR DESCRIPTION
**Pull request by vbudhram**
Taken from https://github.com/vpomerleau/fxa/tree/FXA-6339-storybook-confirm-reset-pw

Because:

- We want to convert content-server views to React and are starting by building out the front-end in Storybook. This PR converts the confirm_reset_password view. Additional complexity will be added in (a) later ticket(s).

This commit:

- Create a new ConfirmPasswordPage in React, with Storybook, Fluent file, and initial metrics and tests.
- Add new PageViewEvent and ViewEvent in amplitude.js

Closes #FXA-6339

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

### CODE REVIEW

**Review by millsoper — APPROVED** [review]
🎉 Looks great!

**Comment by vbudhram** [comment]
Spoke with @vpomerleau and I'm gonna hold off on merging this. There were a couple changes that she wanted to include.

**Comment by vpomerleau** [comment]
Thanks for holding on merging this, @vbudhram. I've pushed changes to my fork, the updated contributor PR is here: https://github.com/mozilla/fxa/pull/14615

**Review by bcolsson — APPROVED** [review]

**Comment by vbudhram** [comment]
I've pushed the latest changes, merging

**Pull request merged**
