### PR TITLE
Revert "chore(deps): bump react-dom from 16.14.0 to 17.0.2"

### PR DESCRIPTION
**Pull request by StaberindeZA**
Reverts mozilla/fxa#12036

### CODE REVIEW

**Comment by LZoog** [comment]
What's the context for needing a revert here?

**Comment by StaberindeZA** [comment]
It could be local to just me, but `payments` pages aren't opening. [Running into an error mentioned here](https://stackoverflow.com/questions/64460098/react-dom-17-0-0-update-error-typeerror-init-is-not-a-function).

**Comment by StaberindeZA** [comment]
> What's the context for needing a revert here?

@LZoog it looks like this change is what's causing the circle-ci tests to fail. After reverting, circle-ci is passing again.

Could you take a look and see if you agree?

**Comment by LZoog** [comment]
> [Running into an error mentioned here](https://stackoverflow.com/questions/64460098/react-dom-17-0-0-update-error-typeerror-init-is-not-a-function).

Ah, we might need to upgrade React _with_ this update of react-dom. Seems fine to revert if it fixes the problem, we should file a follow up maintenance issue to capture that we need to manually upgrade these together.

**Review by LZoog — APPROVED** [review]
r+ though not sure we need the last two commits, if this all gets squashed into one commit before merge it should be fine though - just want to make this easy to cherry-pick since I think we might need a dot release, if that dependabot PR made it into `main` before Ivo tagged

**Pull request merged**
