### PR TITLE
Train 226 uplift 2

### PR DESCRIPTION
**Pull request by dschom**
Connection pooling issues were detected on production. The admin panel refactor most likely triggered this. Reverting the admin panel refactor and dependent PRs.

### CODE REVIEW

**Comment by LZoog** [comment]
Do we need to revert [8a0332c](https://github.com/mozilla/fxa/pull/12024/commits/8a0332c8e3ee34b6b44bd2b80ca530f5fa798cbd)?

Btw it's certainly not worth changing the branch name for but you could update the PR title to "uplift 2", since what's going to get tagged out of this is 226.2. We probably also want to merge #12022 before merging this.

**Comment by dschom** [comment]
@LZoog Thanks for the feedback. I've merged #12022 into main. Concerning [0f674e9](https://github.com/mozilla/fxa/pull/12024/commits/0f674e989d7191064bb6170640d2e76c1d06c6cf), it was part of the change set and a direct result of changes in [41e407d](https://github.com/mozilla/fxa/pull/12024/commits/41e407d233b43120c3c23ff7fce4a75740e3227d), so I think it's best/safest to revert it as well. PR title updated accordingly.

**Comment by LZoog** [comment]
@dschom I think [20aae08](https://github.com/mozilla/fxa/pull/12024/commits/20aae081581ce0424d89f8b235a99a5292020515) snuck in here and should be removed?

**Review by LZoog — APPROVED** [review]
LGTM

**Pull request merged**
