### PR TITLE
chore(docs): Add results and next steps for FxA-49 - CDN

### PR DESCRIPTION
**Pull request by shane-tomlinson**

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
fixes mozilla/fxa-features#7

**Comment by shane-tomlinson** [comment]
@rfk and @davismtl - mind reviewing?

**Comment by rfk** [comment]
This is great, thanks @shane-tomlinson, r+ from me!

The discrepancy between the two metrics is fascinating, I wonder if it's a statistical artifact of using the median for this, and whether we'd see more or less of an impact if we looked at the other quartiles.

**Comment by davismtl** [comment]
Really interesting metrics and analysis. Great job @shane-tomlinson 

@rfk brings up an interesting point. I wonder if it is a statistical anomaly. For example, perhaps this improved speed for users with fast connections but made no difference for those with slow connections. It's theoretically possible (just unlikely) that the median wouldn't have moved much but the overall average yes. 

I'm really glad you defined clear next steps. If you created new issues as a result, feel free to link to them.

r+

**Pull request merged**
