### PR TITLE
test(functional-tests): add pass/fail/skip/fixme counts to CIReporter

### PR DESCRIPTION
**Pull request by Trinaa**
## Because

- we want some visibility on the fixme rate (a subset of skip rate) in CI

## This pull request

- adds count information for passed, failed and skipped (with fixme) tests to the output of the CIReporter

## Issue that this pull request solves

Closes: # FXA-9044

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

CI Output Example:
image

## Other information (Optional)

Any other information that is important to this pull request.

The use of this CI output primarily acts as a sanity for the fixme trend we have calculated and graphed in [FxA Functional Test Suite Metrics](https://docs.google.com/spreadsheets/d/1qKwxsSI2RNo-qKZflETtBbyZ9b0ZUB_id2SL17_MmYo/edit#gid=1830381531)

### CODE REVIEW

**Review by pdehaan — APPROVED** [review]
LGTM! Ship it.

**Comment by pdehaan** [comment]
I think you said in the group DM that this is per-reporter (so we'd have to look at each [of the 6] shards for the results).

Is there a future plan to use `merge-reports` in the future to see if those can be merged into a single stat line for the entire run? Or would the Nightly run have a consolidated stat line?

Can't remember the status of the html-reporter and if we'd want the [`merge-reports`](https://timdeschryver.dev/blog/merging-your-playwright-sharded-reports-into-a-single-html-report) (added in v1.37.0 apparently) there too.

**Comment by Trinaa** [comment]
> Is there a future plan to use `merge-reports` in the future to see if those can be merged into a single stat line for the entire run? Or would the Nightly run have a consolidated stat line?

- I'm thinking no, but we can re-evaluate if ever someone adds a merge-report. The problem is that the junit test reporter doesn't report fixme at top level, so calculating the value involves parsing the report. This would add time and complexity to CI which I don't think is ideal. An auxiliary script is probably best, like the one we have populating the FxA Functional Tests. Still having this info at shard level at least allows us to check that the script is parsing correctly.

**Comment by ashrivastava-qa** [comment]
LGTM :)

**Review by ashrivastava-qa — COMMENTED** [review]
LGTM

**Pull request merged**
