### PR TITLE
feat(deps): Use the fxa-js-client from the repo

### PR DESCRIPTION
**Pull request by shane-tomlinson**

### CODE REVIEW

**Comment by philbooth** [comment]
@shane-tomlinson, see the discussion in #941, I don't think this is going to work unless you explicitly copy it into the Docker image, is it?

We hacked together an approach like that for the auth db fwiw, see #796 in case you want to do something similar. But ideally (long-term) I think we'd work towards a single common Docker image for all the node packages, which permits direct `../` dependencies.

**Comment by shane-tomlinson** [comment]
Shoot, I had the fxa-js-client initially installed as a `file:..` and then overwrote that.

**Comment by shane-tomlinson** [comment]
> Shoot, I had the fxa-js-client initially installed as a file:.. and then overwrote that.

No, wait, this was intentional, that's why I added the `npm install ../fxa-js-client` in Dockerfile-build, to see if Docker would copy that in.

**Comment by shane-tomlinson** [comment]
Closing this yet again.

**Pull request closed without merging**
