### PR TITLE
chore(amplitude): Merge complete and success amplitude events into single event named success

### PR DESCRIPTION
**Pull request by sardesam**
## Because

- These events apply to all transactions, not just [3DS](https://stripe.com/docs/billing/migration/strong-customer-authentication#what-is) transactions.

## This pull request

- Removes all code related to `3ds-complete`.
- Renames `3ds-success` to `success`.
- Updates all applicable tests.

## Issue that this pull request solves

Closes: FXA-6958

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

## Other information (Optional)

This PR works off updates done in #15116, where missing tests for `fail`, `complete`, and `success` were first added.

### CODE REVIEW

**Review by xlisachan — COMMENTED** [review]
Remove L29 in `fxa-payments-server/src/lib/amplitude.test.ts`?

**Comment by sardesam** [comment]
> Remove L29 in `fxa-payments-server/src/lib/amplitude.test.ts`?

Fixed!

**Review by xlisachan — APPROVED** [review]
r+!

**Comment by sardesam** [comment]
> @sardesam : The changes look good! Thank you. (sadly there's still at least one `*3ds*` event in the code, but it's neither a fail nor a success event, and it isn't important for our purposes currently).
> 
> As I mentioned in Lisa's PR, [#15116 (review)](https://github.com/mozilla/fxa/pull/15116#pullrequestreview-1375150610), can you and Lisa please identify what additional event names were modified compared to what was previously described in your tickets and reply to Marnie's reminder Slack post to this effect, CCing Yeonjoo Yoo? Please reference the event names as they show up in the logs, as opposed to the names we use internally that don't show up in the logs.

Thank you @biancadanforth and @xlisachan !

**Pull request merged**
