### PR TITLE
chore(storybooks): switch to a new shared Storybook publisher

### PR DESCRIPTION
**Pull request by lmorchard**
Because

* We want to publish Storybook builds to preview component work

This commit

* Integrates [mozilla-fxa/storybook-gcp-publisher](github.com/mozilla-fxa/storybook-gcp-publisher) into the CircleCI flow so that Storybooks are built and published to a Google Cloud static site for every test run

EXP-281

### CODE REVIEW

**Comment by lmorchard** [comment]
Opening as draft until I see a successful CI run. Hopefully my env vars and GCP permissions are all correct

**Comment by lmorchard** [comment]
Took a few repeats of auth-server tests to get past an intermittent failure, but:

https://storage.googleapis.com/mozilla-storybooks-fxa/commits/17b20992923bbdb3d3abf8a524a8c5ed54057811/index.html

Should also be linked in the "All checks have passed" section as "Details" for "storybooks: pull request"

**Comment by lmorchard** [comment]
I also just tried spreading the Owner role on the Google Cloud project where this site lives. Hopefully that reduces the bus factor a bit. The Github side of things just requires a Personal Access Token from anyone with commit access to the repos, which can be created with access to just post status checks.

I already created all the credentials and env vars, but in case anything goes wrong other folks should have the keys.

**Review by LZoog — APPROVED** [review]
Fantastic work on this. 🙌

**Pull request merged**
