### PR TITLE
chore(strings): fix comment issue in fxa-settings ftl file

### PR DESCRIPTION
**Pull request by bcolsson**
## Because

- Current comment is single message only so localizers will be unable to see comment for all applicable strings where variable is used

## This pull request

- Changes existing comment from single message only  to group-level comment

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

**Comment by flodolo** [comment]
It's ironic that we just said "patches with only changes to FTL will never happen" 🤦🏼 

Through be told, we won't need this type of change once we start reviewing patches before they land.

**Review by flodolo — APPROVED** [review]
Adding @mozilla/fxa-devs just in case ;-)

**Review by clouserw — APPROVED** [review]

**Comment by clouserw** [comment]
> It's ironic that we just said "patches with only changes to FTL will never happen" 🤦🏼

heh, yeah.

@bcolsson go ahead and land this.  The failing tests are because of the atlassian problems

**Comment by bcolsson** [comment]
@clouserw Looks like I'm not authorized to.

**Comment by flodolo** [comment]
> @bcolsson go ahead and land this. The failing tests are because of the atlassian problems

I think Bryan and I can't land this because of branch protections, you probably can override it.

Schermata 2022-06-03 alle 19 30 11

**Comment by clouserw** [comment]
Ah, I forgot that check.  I will land it.

**Comment by clouserw** [comment]
Thanks for the patch @bcolsson !

**Pull request merged**
