### PR TITLE
fix(chore): use the latest version of Firefox in CI testing

### PR DESCRIPTION
**Pull request by jaredhirsch**
🤦

### CODE REVIEW

**Review by vbudhram — APPROVED** [review]
LGTM, only thing was whether we want ESR or latest Firefox.

**Review by dannycoates — APPROVED** [review]
reminder: deploying this is a manual thing... https://github.com/mozilla/fxa/blob/main/_dev/docker/circleci/README.md

**Comment by vbudhram** [comment]
@dannycoates @jaredhirsch looks like content-server tests were skipped, is there an easy way to force those tests to run?

**Comment by dannycoates** [comment]
@vbudhram this circle run isn't using these changes so it doesn't matter

**Pull request merged**
