### PR TITLE
Add a section on security properties to the pairing architecture doc.

### PR DESCRIPTION
**Pull request by rfk**
## Because

* The only current description of the security considerations that
  went into designing the pairing flow, are tucked away in a section
  of the "Phase 1 Project Plan" google doc.
* Google docs are not very discoverable and can have permission
  management issues.

## This pull request

* Copies the relevant security discussion into the long-lived doc
  in the github repo.
* Does a bit of light editing for clairty.

## Issue that this pull request solves

No issue.

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My commit is GPG signed.
    - Oh no, I had cleverly put my GPG root key in offline storage with a randomly generated password and then printed the password and put it in a safe place and then made a sub-key for signing things with, but now my sub-key has expired and the printed-out password doesn't work for some reason and I can't GPG sign things anymore and I have been putting off doing the whole key-revocation-and-regeneration ceremony for months now and now I have to go do that before I can tick all the boxes here to submit a docs change 😭 
- ~~[ ] If applicable, I have modified or added tests which pass locally.~~
- [x] I have added necessary documentation (if appropriate).
- ~~[ ] I have verified that my changes render correctly in RTL (if appropriate).~~

### CODE REVIEW

**Comment by chenba** [comment]
Thanks for the write-up! I'll leave the actual reviewing to people who are more familiar with Pairing.

**Comment by rfk** [comment]
> people who are more familiar with Pairing.

(👀 looks around nervously 👀)

Honestly, I don't know if we have any such people left at Mozilla 😬
But I'll be happy if we have volunteers who would like to become such people!

**Comment by clouserw** [comment]
I'm also not qualified to review, but thanks for writing this.  The words you wrote make sense :)

**Comment by rfk** [comment]
It occurs to me that I should have shared a [link to the section of the Google Doc from which this was summarized](https://docs.google.com/document/d/1mFf0sfEK8o1csXLeyK1x4GS9SUMIq4q8bu25LiydPew/edit#heading=h.ur0lafl8z0a0). It's not a direct copy-and-paste but he broad strokes are all the same.

**Comment by 6a68** [comment]
@rfk sure, I'll take the bait. Let's talk about Pairing sometime soon :-) I'll review the GDoc and this PR in the meantime

**Review by vbudhram — APPROVED** [review]
Thanks documenting @rfk, it matches my rough understanding of the security properties of pairing.

**Pull request merged**
