### PR TITLE
fix(CI): check payments server before tests in CI

### LINKED ISSUE #1947: Check Payments Server's Health in test-content-server.sh
A webpack plugin was throwing a warning (log below) that was treated as an error in CI because the `CI` env var was set.  This was blocking the payments server from starting.  It went unnoticed because nothing was making requests to the payments server in CI at the time.

The issue that generated the warning was fixed in #1843.  But we should `check` the payments server's health in [`test-content-server.sh`](https://github.com/mozilla/fxa/blob/master/.circleci/test-content-server.sh#L8).

```
chunk 0 [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/components/DialogMessage.scss
 * css ./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/components/Portal.scss
```

### PR DESCRIPTION
**Pull request by chenba**
Fixes #1947

### CODE REVIEW

**Comment by lmorchard** [comment]
Hmm, payments server should have its own set of tests, separate from test-content-server. Is this the right spot for it?

**Comment by 6a68** [comment]
oh, @lmorchard has a good point. maybe there's a better spot for that check?

**Comment by chenba** [comment]
A few of the functional tests in `test-content-server` rely on the payments server being up.  That's the main reason for this.

**Comment by lmorchard** [comment]
> A few of the functional tests in test-content-server rely on the payments server being up.

Ah, okay, then the cross-over is not so weird.

**Pull request merged**
