### PR TITLE
Train 223 uplift for 223.1

### PR DESCRIPTION
**Pull request by chenba**

### CODE REVIEW

**Comment by LZoog** [comment]
@chenba ack, I'm so sorry for any confusion, [this](https://github.com/mozilla/fxa/pull/11530/) (c15a7937fc575385153eb5a3bc6c55a0453fdc0e) is the PR we need uplifted, not 6ca3be which we reverted 😢

**Comment by chenba** [comment]
> @chenba ack, I'm so sorry for any confusion, [this](https://github.com/mozilla/fxa/pull/11530/) ([c15a793](https://github.com/mozilla/fxa/commit/c15a7937fc575385153eb5a3bc6c55a0453fdc0e)) is the PR we need uplifted, not [6ca3bee](https://github.com/mozilla/fxa/commit/6ca3beeb67f1adc4c7ee16ba15bffca84bbf34f0) which we reverted 😢

Thanks for catching that!

**Comment by LZoog** [comment]
It LGTM now! I can r+ but do you want to tag first so changelogs and such are in the review?

**Comment by chenba** [comment]
> It LGTM now! I can r+ but do you want to tag first so changelogs and such are in the review?

I'm doing this approach: https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/release-process#another-option-for-a-patch-release so I don't think I need another approval for the tag itself.

**Review by LZoog — APPROVED** [review]

**Pull request merged**
