### PR TITLE
chore(style): Remove unused images in fxa-content-server/app/images

### PR DESCRIPTION
**Pull request by krtb**
Remove the following image files, from folder located in path, `fxa-content-server/app/images`
- `graphic_mail.png`
- `graphic_mail@2x.png`
- `account-verified.png`
- all files that start with `ddarrow`

Fixes issue [#2554](https://github.com/mozilla/fxa/issues/2554)
May overlap with issue [#1878](https://github.com/mozilla/fxa/issues/1878)

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@krtb - these changes look good and have been approved, unfortunately a couple of small changes need to be made so that we can merge. 

* Rebasing from the current master should fix the test failure.
* Can you set up [GPG commit signing](https://help.github.com/articles/managing-commit-signature-verification) and sign the commit?

**Comment by krtb** [comment]
thanks Shane, I have two questions.

When rebasing from current master, I do `git pull --rebase origin master` from my branch or the master branch?

And I setup my GDP, but how can I sign without creating further commits? The explanation I found, `git commit -S -m your commit message#`, involves signing a new commit. Is there a way to create an empty commit to do this?

**Comment by shane-tomlinson** [comment]
> When rebasing from current master, I do git pull --rebase origin master from my branch or the master branch?

First, go to your master branch and do a `git pull --rebase origin master`. Then checkout your branch and do a `git rebase master`.

> And I setup my GPG, but how can I sign without creating further commits? 

You can do a `git commit --amend` and then save the commit message without changing the text. It'll ask for your GPG password once you save.

**Comment by krtb** [comment]
Thanks for the walk through @shane-tomlinson (: 

I rebased and added my gpg signature. Although I don't understand why the `fxa-email-service` check is failing the circleci test. Please let me know if I have to do something on my end for that.

**Pull request merged**
