### PR TITLE
chore(docs): add a top level AUTHORS file with all contributors

### PR DESCRIPTION
**Pull request by shane-tomlinson**
This also adds an `npm run authors` script to package.json and
removes the content-server's author grunttask.

I would like to add this to @philbooth's release.sh script,
but wasn't sure where it would best go.

@philbooth - any pointers on adding this to the release script?

### CODE REVIEW

**Comment by philbooth** [comment]
> any pointers on adding this to the release script?

I'd probably stick it immediately before the `git commit`, so that it gets added with all the changelogs and version bumps.

**Comment by shane-tomlinson** [comment]
@philbooth updated release.sh, mind having a look?

**Comment by philbooth** [comment]
> updated release.sh, mind having a look?

Looks good, thanks.

**Comment by shane-tomlinson** [comment]
@philbooth - squashed the commits, AND made the commit message compliant.

**Pull request merged**
