### PR TITLE
Bug No. 7766 is resolved

### PR DESCRIPTION
**Pull request by amantayal6797**
## Because

- Check shade/opacity of confirmation pointer thingy

## This pull request

- solves the above bug

## Issue that this pull request solves

Closes: #9156

## Checklist

_Put an `x` in the boxes that apply_

- [x ] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.
image

## Other information (Optional)

Any other information that is important to this pull request.

### CODE REVIEW

**Comment by dannycoates** [comment]
Thank you @amantayal6797, it looks good. Could you remove `tailwind.out.scss` and squash this into one commit please?

**Comment by amantayal6797** [comment]
I had to made two changes in tailwind.out.scss to resolve this bug. If I removed this file then my changes in index.tsx will break.

**Comment by dannycoates** [comment]
> If I removed this file then where I have to make changes?

ah, ok. If you add a value for 700 here: https://github.com/mozilla/fxa/blob/main/packages/fxa-react/configs/tailwind.js#L161 and change this line https://github.com/mozilla/fxa/blob/main/packages/fxa-react/configs/tailwind.js#L299 I think that'll work.

**Comment by amantayal6797** [comment]
@dannycoates thank you for your help. I made the changes which are suggested by you in last reply. As I don't know how mention those changes here. I created a two more PR.
https://github.com/mozilla/fxa/pull/8786
https://github.com/mozilla/fxa/pull/8787
Please suggest me. If any further changes is required and please merge my PR.

**Comment by vbudhram** [comment]
Closing this in favor of the other two related PRs by user.

**Pull request closed without merging**
