### PR TITLE
chore(test perf): log the duration of auth test server start/stop

### PR DESCRIPTION
**Pull request by chenba**

### CODE REVIEW

**Comment by chenba** [comment]
@dschom opened as a draft with some simple console.logs to see there are noticeable patterns.  Did you want to actually merge something into main or was your plan to cherry-pick onto the Sentry changes to get some perf numbers and close this without merging?

Locally the first test suite took longer than the rest to to start.  After two runs in CI, looks like the first and last test suite took longer to start and stop.  And there's another suite that I have yet to identify that took longer than others to stop.

I using auth-server's `test-integration` for these tests.  I think the first test suite to is `fxa/packages/fxa-auth-server/test/remote/account_create_tests.js`, and the last is `fxa/packages/fxa-auth-server/test/scripts/check-users.js`.  (In other words alphabetical.)  

Here's how long the starts were on the initial CI integration test run:

```
test server perf - 1530fd00-30a8-43ab-9962-ca20c6c55159-start took ms: 13308.477268000002
test server perf - b288f76d-173a-4647-93be-819d28af564d-start took ms: 230.86846200000218
test server perf - 086949a6-d546-49e7-9cb8-74f0ea052e5f-start took ms: 198.20062499999767
test server perf - 2f6d2576-5bb2-4bb5-8a25-c50800a38b32-start took ms: 203.06970699999874
test server perf - 244e671a-d2cf-4a36-ae69-cd18deb29fa6-start took ms: 184.85524200000145
test server perf - 66ff4b36-8e06-4360-a939-0daf8444b77c-start took ms: 169.6858629999988
test server perf - 060c67cf-9a54-4939-ba0d-6b326d522718-start took ms: 184.85361000000557
test server perf - faa8beea-ed74-4672-9987-76697b221279-start took ms: 209.3031090000004
test server perf - 1b3237d8-41c3-48ba-8345-656292199a1c-start took ms: 179.88460599999962
test server perf - bf80de89-167d-44fa-8d81-720fac812ac5-start took ms: 178.84970500000054
test server perf - 76228a09-95af-4b92-9e26-c271cac5b372-start took ms: 174.30032900000515
test server perf - 46d29243-7ff6-4153-ad04-ed956a774701-start took ms: 173.1620249999978
test server perf - bfc34819-4e3b-4c4c-8eef-2e247182ab3d-start took ms: 174.12344199999643
test server perf - a8e7ea15-ac74-4718-af2b-f3ed248722e3-start took ms: 172.68884600000456
test server perf - b8be2f59-3baf-4af6-b327-1a6f0123ff6b-start took ms: 178.58603199999925
test server perf - 1be95be6-1b74-41b9-b415-d3e1f748b26d-start took ms: 175.4851340000023
test server perf - 1a5b2b09-0084-4036-b131-ee4629a83453-start took ms: 183.6373569999996
test server perf - d6c62706-6f97-4b60-9bc5-723aee628ee2-start took ms: 182.45315799999662
test server perf - 4aa8ff6e-2826-47ac-896f-591906679636-start took ms: 179.9379919999992
test server perf - 04f76537-d0ae-44a9-9def-30796392a972-start took ms: 180.55258799999865
test server perf - dd8dbb4c-4ff3-4083-902f-9bdde5ab72c2-start took ms: 181.30620099999942
test server perf - 70ddc4f2-5123-44ed-852b-85b39e44447d-start took ms: 187.14731799999572
test server perf - 7378d1a5-b8ff-43a1-9a30-ed9b9b3cc598-start took ms: 181.17024700000184
test server perf - 2ea9a71d-cc77-4304-8352-20f01f539a6d-start took ms: 185.92294499999844
test server perf - b2d9456e-3549-4220-a4ea-b4d7efb527e0-start took ms: 186.569614
test server perf - 89f66be5-adbb-4a59-a476-b30e5c9c55e3-start took ms: 184.93175999999949
test server perf - b1724b93-ab63-4f05-9fdb-dd6b6e36b873-start took ms: 181.64542200000142
test server perf - cf90db7c-cc72-4a75-897a-c15ea7606bcf-start took ms: 203.63363900000695
test server perf - 4fc31496-85c9-4c7c-9852-3b5ba772b239-start took ms: 177.97226099998807
test server perf - 27f71026-0716-4967-85de-6f51c537c6ab-start took ms: 181.2168629999942
test server perf - 2c026a33-e7ca-4f01-9f17-a7e5b449680f-start took ms: 177.24996199998714
test server perf - 6379728b-f8fb-4a64-a4b5-7dbbfd7439c0-start took ms: 180.77042300000903
test server perf - 049215fb-034b-4aba-bd41-a23a303bdf93-start took ms: 188.1298139999999
test server perf - 4382c85c-1c9e-4db2-b855-21eb09221720-start took ms: 172.40222200000426
test server perf - 6005d2a2-b383-4e83-9af8-093f0fbadcce-start took ms: 194.4949900000065
test server perf - 5123502b-c339-416a-8186-628f3a4ceb60-start took ms: 198.99800000000687
test server perf - a94efab4-ab75-4e4b-8a6b-970ecbe4eedd-start took ms: 237.23501099999703
test server perf - 62c62285-bf60-4505-942f-77867c5b2cda-start took ms: 198.0460030000104
test server perf - 7c3b69d8-675b-4e2a-9ca4-e75f6d740f0e-start took ms: 193.83423500000208
test server perf - a741a970-caf8-4a0a-87b4-31b23e8df32c-start took ms: 183.3013659999997
test server perf - 8bfb7f05-4f65-4369-aaf4-d1808cfaa976-start took ms: 179.23881899999105
test server perf - ec8aa34d-1751-4bf4-8626-4faba283ea5a-start took ms: 176.01413999999932
test server perf - 1e7be0c1-0b60-4364-8d9b-9822a5d0ba74-start took ms: 14429.390139
```

stops

```
test server perf - 1530fd00-30a8-43ab-9962-ca20c6c55159-stop took ms: 1.7370800000026065
test server perf - b288f76d-173a-4647-93be-819d28af564d-stop took ms: 0.8543890000000829
test server perf - 086949a6-d546-49e7-9cb8-74f0ea052e5f-stop took ms: 0.888887999997678
test server perf - 2f6d2576-5bb2-4bb5-8a25-c50800a38b32-stop took ms: 0.6237340000006952
test server perf - 244e671a-d2cf-4a36-ae69-cd18deb29fa6-stop took ms: 0.6568829999996524
test server perf - 66ff4b36-8e06-4360-a939-0daf8444b77c-stop took ms: 0.6505229999966105
test server perf - 060c67cf-9a54-4939-ba0d-6b326d522718-stop took ms: 0.9027550000027986
test server perf - faa8beea-ed74-4672-9987-76697b221279-stop took ms: 0.3749150000003283
test server perf - 1b3237d8-41c3-48ba-8345-656292199a1c-stop took ms: 0.7143409999989672
test server perf - bf80de89-167d-44fa-8d81-720fac812ac5-stop took ms: 0.6899130000019795
test server perf - 76228a09-95af-4b92-9e26-c271cac5b372-stop took ms: 0.5651349999970989
test server perf - 46d29243-7ff6-4153-ad04-ed956a774701-stop took ms: 0.6354600000049686
test server perf - bfc34819-4e3b-4c4c-8eef-2e247182ab3d-stop took ms: 0.3682849999968312
test server perf - a8e7ea15-ac74-4718-af2b-f3ed248722e3-stop took ms: 0.83052399999724
test server perf - b8be2f59-3baf-4af6-b327-1a6f0123ff6b-stop took ms: 0.5052399999985937
test server perf - 1be95be6-1b74-41b9-b415-d3e1f748b26d-stop took ms: 0.7518210000052932
test server perf - 1a5b2b09-0084-4036-b131-ee4629a83453-stop took ms: 0.5335330000016256
test server perf - d6c62706-6f97-4b60-9bc5-723aee628ee2-stop took ms: 26.903635000002396
test server perf - 4aa8ff6e-2826-47ac-896f-591906679636-stop took ms: 0.7789770000017597
test server perf - 04f76537-d0ae-44a9-9def-30796392a972-stop took ms: 0.639655999999377
test server perf - dd8dbb4c-4ff3-4083-902f-9bdde5ab72c2-stop took ms: 0.7294140000012703
test server perf - 70ddc4f2-5123-44ed-852b-85b39e44447d-stop took ms: 0.6518739999955869
test server perf - 7378d1a5-b8ff-43a1-9a30-ed9b9b3cc598-stop took ms: 0.6550029999998515
test server perf - 2ea9a71d-cc77-4304-8352-20f01f539a6d-stop took ms: 0.7985350000017206
test server perf - b2d9456e-3549-4220-a4ea-b4d7efb527e0-stop took ms: 0.46217500000057044
test server perf - 89f66be5-adbb-4a59-a476-b30e5c9c55e3-stop took ms: 0.7933049999992363
test server perf - b1724b93-ab63-4f05-9fdb-dd6b6e36b873-stop took ms: 2.2545790000003763
test server perf - cf90db7c-cc72-4a75-897a-c15ea7606bcf-stop took ms: 0.9187479999964125
test server perf - 4fc31496-85c9-4c7c-9852-3b5ba772b239-stop took ms: 0.5618859999958659
test server perf - 27f71026-0716-4967-85de-6f51c537c6ab-stop took ms: 0.62105000000156
test server perf - 2c026a33-e7ca-4f01-9f17-a7e5b449680f-stop took ms: 0.7596670000057202
test server perf - 6379728b-f8fb-4a64-a4b5-7dbbfd7439c0-stop took ms: 0.6317370000033407
test server perf - 049215fb-034b-4aba-bd41-a23a303bdf93-stop took ms: 0.6223879999888595
test server perf - 4382c85c-1c9e-4db2-b855-21eb09221720-stop took ms: 1.1482649999961723
test server perf - 6005d2a2-b383-4e83-9af8-093f0fbadcce-stop took ms: 0.4208199999993667
test server perf - 5123502b-c339-416a-8186-628f3a4ceb60-stop took ms: 0.5529430000024149
test server perf - a94efab4-ab75-4e4b-8a6b-970ecbe4eedd-stop took ms: 0.7372799999866402
test server perf - 62c62285-bf60-4505-942f-77867c5b2cda-stop took ms: 0.7866330000106245
test server perf - 7c3b69d8-675b-4e2a-9ca4-e75f6d740f0e-stop took ms: 0.8809570000012172
test server perf - a741a970-caf8-4a0a-87b4-31b23e8df32c-stop took ms: 0.6682809999911115
test server perf - 8bfb7f05-4f65-4369-aaf4-d1808cfaa976-stop took ms: 0.6240690000122413
test server perf - ec8aa34d-1751-4bf4-8626-4faba283ea5a-stop took ms: 0.47345099999802187
test server perf - 1e7be0c1-0b60-4364-8d9b-9822a5d0ba74-stop took ms: 2.3830089999974007
```

**Comment by chenba** [comment]
For Sentry 8 I first cherry-picked onto commit 83dc649b528240bab0566cfc4f9563892b32ebca, here are the results from that CI run

starts

```
test server perf - e5b0f64c-20e4-4055-8a48-d6e16972815f-start took ms: 30089.279387
test server perf - 1f8eb933-d576-42b6-8e42-ab840d7e2525-start took ms: 347.05553099999815
test server perf - 8a0c1aed-8b30-4835-97eb-1dfc004d030e-start took ms: 244.5323419999986
test server perf - a226f709-2705-491d-9f7b-bc0521e4e7cf-start took ms: 240.2700859999968
test server perf - 84adeb6c-1d35-4e38-b833-e641b2b80656-start took ms: 245.48670099999435
test server perf - e75c8201-a1ef-4ea8-80cf-0412eb1344e2-start took ms: 219.4927949999983
test server perf - 2c249905-3bf9-4959-8430-912665a36bc4-start took ms: 229.27255600000353
test server perf - 5ac27af9-7985-4947-8919-c004218b58ad-start took ms: 262.4983060000013
test server perf - 85be0ede-965e-4f0e-a750-4c1b6604cf89-start took ms: 268.7939239999978
test server perf - 4b2ab917-6d7f-47c0-b8b8-3b29c51e85e8-start took ms: 230.00864600000205
test server perf - 38f706f8-9f1c-4f5a-aed6-9148f31ca264-start took ms: 229.49011400000018
test server perf - ea0d59bb-2bfc-4436-b229-9738027bc3b0-start took ms: 224.52580599999055
test server perf - 65645c4d-db98-476a-8f32-19af3b98652b-start took ms: 223.1232239999954
test server perf - 60148c3b-30e1-43a4-a723-1799747fb44e-start took ms: 224.48425799999677
test server perf - 2da98bb9-a113-4fbf-a2c2-5ccd62ef38d5-start took ms: 219.69571899999573
test server perf - bb5ea0bc-823a-4572-8122-5f6491c175a5-start took ms: 217.8467510000046
test server perf - d7cb5111-ab6f-4702-94aa-03c8a2c83f29-start took ms: 223.65306599999894
test server perf - 2407e3a9-922b-4a5b-bb4e-4701af38b01c-start took ms: 222.68389900001057
test server perf - 4b01b11d-5605-4d28-9a40-820156612c5b-start took ms: 225.899442000009
test server perf - 46b4bb2f-5637-4d79-a162-02ebb581062c-start took ms: 225.06397699999798
test server perf - fa0db441-4f9b-4aa0-a02e-6a546415b2c8-start took ms: 225.0453989999951
test server perf - d560b354-835f-4fa8-8217-e35c53224fa8-start took ms: 221.60320100000536
test server perf - 01a21c94-4133-412f-a633-dbe0c061920c-start took ms: 274.60892500000773
test server perf - 2afd1408-4b20-46aa-9a21-7e28f59677f3-start took ms: 287.1113449999975
test server perf - 204e981f-1924-41c4-a63f-96f91ab6a688-start took ms: 219.917294999992
test server perf - 3bf82106-7366-4881-9306-c3f711ae3022-start took ms: 218.3685359999945
test server perf - 13501748-a37d-4ae9-9ca7-a5230469b01f-start took ms: 221.7802079999965
test server perf - 15705bc0-8226-4432-a8c3-52792f19d939-start took ms: 234.972563000003
test server perf - bdb33b21-5e9e-41a6-a73d-c0a5cc2cf010-start took ms: 229.55782299999555
test server perf - 39f328c6-ee4d-41da-9b19-ed502965089f-start took ms: 225.2855869999912
test server perf - 8fb89b6a-6b83-4082-a2f9-57debf047f8c-start took ms: 223.48451399999612
test server perf - 353fcf6a-ced9-4ef2-b8af-af4f065674d3-start took ms: 222.02847900000052
test server perf - d05d4ce6-f174-4661-b7f0-f7c37e07aa82-start took ms: 232.17376100001275
test server perf - 310457e9-e7d6-4d1d-b0e2-35c477e2bff7-start took ms: 282.3647099999944
test server perf - 95a73e5d-c38d-4022-b94e-39a8bcc56d6f-start took ms: 230.04950299998745
test server perf - dfb43111-a528-46a5-a89b-676596853f9c-start took ms: 306.3514950000099
test server perf - b69d11e0-4a68-405a-9d4a-5fee8a65435e-start took ms: 201.09629600000335
test server perf - 201526a2-930a-410d-af4f-6ad06be11d92-start took ms: 225.99070299998857
test server perf - bfdd38c5-a711-4305-b1fa-a5c23a16d03e-start took ms: 230.85095799999544
test server perf - 9287ebd5-0bdc-4bdd-8bfb-bbbb154640ca-start took ms: 220.91464400000405
test server perf - 4fdeb4d2-3a5a-45c0-b6c8-522679580f08-start took ms: 222.72137699997984
test server perf - 47bdd25e-0ef2-401a-90c5-fa2b01712fab-start took ms: 224.64279799998621
test server perf - cc4c5d2c-339c-415e-80cb-7d1a437d2fb4-start took ms: 28829.452172999998
```

stops
```
test server perf - e5b0f64c-20e4-4055-8a48-d6e16972815f-stop took ms: 2.5590440000014496
test server perf - 1f8eb933-d576-42b6-8e42-ab840d7e2525-stop took ms: 1.2315529999978025
test server perf - 8a0c1aed-8b30-4835-97eb-1dfc004d030e-stop took ms: 1.0387059999993653
test server perf - a226f709-2705-491d-9f7b-bc0521e4e7cf-stop took ms: 0.6803559999971185
test server perf - 84adeb6c-1d35-4e38-b833-e641b2b80656-stop took ms: 0.8933780000006664
test server perf - e75c8201-a1ef-4ea8-80cf-0412eb1344e2-stop took ms: 0.8763929999986431
test server perf - 2c249905-3bf9-4959-8430-912665a36bc4-stop took ms: 0.8163690000001225
test server perf - 5ac27af9-7985-4947-8919-c004218b58ad-stop took ms: 0.5784529999946244
test server perf - 85be0ede-965e-4f0e-a750-4c1b6604cf89-stop took ms: 0.9361510000017006
test server perf - 4b2ab917-6d7f-47c0-b8b8-3b29c51e85e8-stop took ms: 0.8602339999997639
test server perf - 38f706f8-9f1c-4f5a-aed6-9148f31ca264-stop took ms: 0.9423640000022715
test server perf - ea0d59bb-2bfc-4436-b229-9738027bc3b0-stop took ms: 0.9163570000091568
test server perf - 65645c4d-db98-476a-8f32-19af3b98652b-stop took ms: 0.4639680000109365
test server perf - 60148c3b-30e1-43a4-a723-1799747fb44e-stop took ms: 0.8118200000026263
test server perf - 2da98bb9-a113-4fbf-a2c2-5ccd62ef38d5-stop took ms: 0.5698050000064541
test server perf - bb5ea0bc-823a-4572-8122-5f6491c175a5-stop took ms: 1.5432809999911115
test server perf - d7cb5111-ab6f-4702-94aa-03c8a2c83f29-stop took ms: 0.7107830000022659
test server perf - 2407e3a9-922b-4a5b-bb4e-4701af38b01c-stop took ms: 36.13915200000338
test server perf - 4b01b11d-5605-4d28-9a40-820156612c5b-stop took ms: 0.7562460000044666
test server perf - 46b4bb2f-5637-4d79-a162-02ebb581062c-stop took ms: 0.9285749999980908
test server perf - fa0db441-4f9b-4aa0-a02e-6a546415b2c8-stop took ms: 0.7577230000024429
test server perf - d560b354-835f-4fa8-8217-e35c53224fa8-stop took ms: 0.7682869999989634
test server perf - 01a21c94-4133-412f-a633-dbe0c061920c-stop took ms: 0.7898579999891808
test server perf - 2afd1408-4b20-46aa-9a21-7e28f59677f3-stop took ms: 0.6816770000004908
test server perf - 204e981f-1924-41c4-a63f-96f91ab6a688-stop took ms: 0.5962760000111302
test server perf - 3bf82106-7366-4881-9306-c3f711ae3022-stop took ms: 0.8841149999934714
test server perf - 13501748-a37d-4ae9-9ca7-a5230469b01f-stop took ms: 2.9334690000105184
test server perf - 15705bc0-8226-4432-a8c3-52792f19d939-stop took ms: 1.1205520000075921
test server perf - bdb33b21-5e9e-41a6-a73d-c0a5cc2cf010-stop took ms: 0.7352779999928316
test server perf - 39f328c6-ee4d-41da-9b19-ed502965089f-stop took ms: 0.7607089999946766
test server perf - 8fb89b6a-6b83-4082-a2f9-57debf047f8c-stop took ms: 0.8740919999981998
test server perf - 353fcf6a-ced9-4ef2-b8af-af4f065674d3-stop took ms: 1.1982799999823328
test server perf - d05d4ce6-f174-4661-b7f0-f7c37e07aa82-stop took ms: 1.3878740000072867
test server perf - 310457e9-e7d6-4d1d-b0e2-35c477e2bff7-stop took ms: 0.8363490000192542
test server perf - 95a73e5d-c38d-4022-b94e-39a8bcc56d6f-stop took ms: 0.545096999994712
test server perf - dfb43111-a528-46a5-a89b-676596853f9c-stop took ms: 0.9938839999958873
test server perf - b69d11e0-4a68-405a-9d4a-5fee8a65435e-stop took ms: 0.696235000010347
test server perf - 201526a2-930a-410d-af4f-6ad06be11d92-stop took ms: 0.7985439999902155
test server perf - bfdd38c5-a711-4305-b1fa-a5c23a16d03e-stop took ms: 0.8407160000060685
test server perf - 9287ebd5-0bdc-4bdd-8bfb-bbbb154640ca-stop took ms: 0.6790969999856316
test server perf - 4fdeb4d2-3a5a-45c0-b6c8-522679580f08-stop took ms: 0.8096329999971204
test server perf - 47bdd25e-0ef2-401a-90c5-fa2b01712fab-stop took ms: 0.6418019999982789
test server perf - cc4c5d2c-339c-415e-80cb-7d1a437d2fb4-stop took ms: 2.260830999999598
```

**Comment by chenba** [comment]
@dschom the test server does take longer to start with the Sentry 8 changes.  But I think you mentioned that it got progressively slower, which I'm not seeing.  (Unless you meant the tests got progressively slower and not the server starts?)

**Comment by dschom** [comment]
> @dschom the test server does take longer to start with the Sentry 8 changes. But I think you mentioned that it got progressively slower, which I'm not seeing. (Unless you meant the tests got progressively slower and not the server starts?)

I was seeing was that the last test was taking much longer that others to start and this was causing timeout failures. If used the word progressively, I mispoke. What's probably good news is that we definitely see a big jump due to sentry 8. 

For now, perhaps increase timeouts on the first and last test suite, is a minimal change to get this landed?

**Pull request closed without merging**
