### PR TITLE
align category headers to subcategroies

### PR DESCRIPTION
**Pull request by Jo-bot86**
## Because

- category header Profile and Security are not aligned to subcategory headers

## This pull request

- sets margin-left for Profile and Security to ltr:ml-6 and rtl:mr-6

## Issue that this pull request solves

Closes: #7755

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

screenshot before and after changes
grafik
grafik

## Other information (Optional)

Any other information that is important to this pull request.

I left  Connected Services as it is, since it's subcategory doesn't have a header.

### CODE REVIEW

**Review by jodyheavener — CHANGES_REQUESTED** [review]
This is looking great! I think we should also apply this consistency to smaller breakpoints as well:

Screen Shot 2021-04-05 at 10 50 51 AM

**Comment by jodyheavener** [comment]
@Jo-bot86 you'll also want to align your commit message with the format we've outlined in [this doc](https://github.com/mozilla/fxa/blob/main/CONTRIBUTING.md#git-commit-guidelines) 😀

**Comment by Jo-bot86** [comment]
@jodyheavener  ups, thanks for the advice :sweat_smile:

**Comment by Jo-bot86** [comment]
> This is looking great! I think we should also apply this consistency to smaller breakpoints as well:
> 
> Screen Shot 2021-04-05 at 10 50 51 AM

Thank you very much for the review. I will do that right away

**Comment by Jo-bot86** [comment]
@jodyheavener I think this should work now. Otherwise I'm happy about advice

**Review by jodyheavener — APPROVED** [review]
Looks great, thank you! 🥳

**Pull request merged**
