### PR TITLE
chore(settings): remove period in one-line alert bar copy

### PR DESCRIPTION
**Pull request by sardesam**
## Because

- We want to maintain consistency of alert bar copy in account settings

## This pull request

- Removes the period from one line alert bar messages

## Issue that this pull request solves

Closes: #9253

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

N/A

## Other information (Optional)

N/A

### CODE REVIEW

**Comment by LZoog** [comment]
Is this really something we want to do? I feel like it would be more consistent to _add_ periods where they're missing, the original copy for Settings alert bar messages had periods. It reads weird to me without a period since they're complete sentences and all of these strings have to be relocalized. Can we confirm with Vesta this is what we want to do?

**Comment by sardesam** [comment]
Thanks, Lauren! I'll contact Vesta to get her input and go from there.

**Comment by LZoog** [comment]
Thanks @sardesam, just to bring some of our Slack convo here - for a recent PR of mine, Vesta confirmed new error message/success message copy and they both had periods, though I didn't specifically call those out. I remember the original Settings copy had periods in the success messaging, so this PR gave me pause due to the number of strings changed; whenever we change them here, they have to be retranslated across all of our locales. It's possible we might be able to do a find-and-replace in the l10n repo to remove these periods to keep the IDs and translations, but I'm not sure how periods work across all locales and we'd have to ask someone from the l10n team if that's possible.

It's fine by me if @clouserw / Vesta want to remove the periods, I just wanted to call out the number of strings this changes vs if we just add them to the couple of spots where they're missing.

**Comment by LZoog** [comment]
@flodolo either way we go here, just so we know for the future - is a punctuation change something that is better handled by creating new FTL IDs as we have done here, or can we save these translations somehow?

**Comment by flodolo** [comment]
> @flodolo either way we go here, just so we know for the future - is a punctuation change something that is better handled by creating new FTL IDs as we have done here, or can we save these translations somehow?

Using new IDs is the right approach, as rules for punctuation change by locale. 

Pontoon's Translation Memory should help avoid losing too much time retranslating these.

**Comment by LZoog** [comment]
> Pontoon's Translation Memory should help avoid losing too much time retranslating these.

Fantastic. Are there any existing docs around how the translation memory works? I'm picturing there being translation suggestions based on a nearly identical string match, that kind of thing would be great to know about or at least have a link to.

@sardesam I may have raised a false alarm here - I know the original Settings copy did have periods so I still personally think it's "more consistent" to change those few that do not have them, but as I've said I defer to Wil/Vesta here. 🙂

**Comment by flodolo** [comment]
> Are there any existing docs around how the translation memory works?

Not that I'm aware, but it's also a feature common to all localization management tools
https://en.wikipedia.org/wiki/Translation_memory

In Pontoon, while translating you will see matches from strings already translated. The percentage is the difference between that match and the string you're translating (Levenshtein distance)
https://en.wikipedia.org/wiki/Levenshtein_distance

Schermata 2022-05-24 alle 06 41 20

**Comment by sardesam** [comment]
@LZoog No false alarm raised. I am glad this issue is getting clarified as it affects both our guidelines and translation process.

On that note, confirmed with Vesta that as per Mozilla's punctuation guidelines, her recommendation is to remove the trailing period on one sentence alerts, and keep it on multi-sentence alerts.

For future reference, in case this ever changes, currently, the lines that contain more than one sentence are:

1. _Thanks! Sharing this data helps us improve Firefox Accounts._
2. _Opt out successful. Firefox Accounts won’t send technical or interaction data to Mozilla._

**Review by bcolsson — APPROVED** [review]
Reviewed all .ftl files, confirmed new IDs for all strings with removed periods.

**Review by LZoog — APPROVED** [review]
LGTM, thanks for dealing with my initial pushback and checking with Vesta 😝

**Pull request merged**
