### PR TITLE
fix(fxa-settings): fix recovery key link

### PR DESCRIPTION
**Pull request by meandavejustice**
## This pull request

- fixes a broken link in secondary email section

## Issue that this pull request solves

Closes: #6372

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).

### CODE REVIEW

**Comment by chenba** [comment]
Couldn't we add an id to the Recovery Key heading and link to that instead?

**Comment by jodyheavener** [comment]
> Couldn't we add an id to the Recovery Key heading and link to that instead?

Yes I would do something like that. When I left my [comment](https://github.com/mozilla/fxa/issues/6372#issuecomment-688467525) I didn't take into account that the sidebar does link to `#security`, so that ID should stay in place.

**Comment by meandavejustice** [comment]
@chenba @jodyheavener Fixed it up

**Review by chenba — APPROVED** [review]
👍

**Pull request merged**
